'use client'

import { useEffect, useMemo, useState } from 'react'

type Product = { _id?: string; name: string; category: string; description: string; image?: string }
type Lead = { name?: string; email?: string; phone?: string; organization?: string; address?: string; message?: string; createdAt?: string }
type Metrics = { visitors: number; quotes: number; daily: number; monthly: number; yearly: number; products: { name: string; clicks: number }[] }
const demoProducts: Product[] = [
  { name: 'Portable Patient Monitor', category: 'Monitoring', description: 'Compact multi-parameter monitor for confident bedside care.' },
  { name: 'LED Surgical Light', category: 'Surgical', description: 'Shadowless illumination with precise, cool LED output.' },
  { name: 'Endoscope X-200', category: 'Diagnostics', description: 'High-definition visualization for modern diagnostic teams.' },
]

export default function AdminPage() {
  const [active, setActive] = useState('Overview')
  const [products, setProducts] = useState<Product[]>([])
  const [leads, setLeads] = useState<Lead[]>([])
  const [metrics, setMetrics] = useState<Metrics>({ visitors: 0, quotes: 0, daily: 0, monthly: 0, yearly: 0, products: [] })
  const [settings, setSettings] = useState({ phone: '', whatsapp: '', email: '' })
  const [message, setMessage] = useState('')
  const [form, setForm] = useState({ name: '', category: '', description: '', image: '' })
  const [newCategory, setNewCategory] = useState(false)
  const nav = ['Overview', 'Products', 'Leads & enquiries', 'Analytics', 'Settings']
  const load = async () => {
    const [p, l, a, s] = await Promise.all([fetch('/api/admin/products'), fetch('/api/admin/quotes'), fetch('/api/admin/analytics'), fetch('/api/admin/settings')])
    if (p.ok) setProducts(await p.json())
    if (l.ok) setLeads((await l.json()).quotes || [])
    if (a.ok) setMetrics(await a.json())
    if (s.ok) setSettings(await s.json())
  }
  useEffect(() => { load() }, [])
  const categories = useMemo(() => Array.from(new Set([...demoProducts.map((p) => p.category), ...products.map((p) => p.category)])), [products])
  const allProducts = products.length ? products : demoProducts
  async function upload(file: File) { const data = new FormData(); data.append('file', file); const r = await fetch('/api/admin/upload', { method: 'POST', body: data }); const result = await r.json(); if (!r.ok) throw new Error(result.error || 'Upload failed'); return result.url }
  async function saveProduct(e: React.FormEvent) { e.preventDefault(); const r = await fetch('/api/admin/products', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (r.ok) { setMessage('Product published.'); setForm({ name: '', category: '', description: '', image: '' }); load() } }
  async function removeProduct(product: Product) { if (!confirm(`Remove ${product.name}?`)) return; const query = product._id ? `id=${encodeURIComponent(product._id)}` : `name=${encodeURIComponent(product.name)}`; const r = await fetch(`/api/admin/products?${query}`, { method: 'DELETE' }); setMessage(r.ok ? 'Product removed.' : 'Could not remove product.'); load() }
  async function saveSettings(e: React.FormEvent) { e.preventDefault(); const r = await fetch('/api/admin/settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(settings) }); setMessage(r.ok ? 'Website settings saved.' : 'Could not save settings.') }
  return <main className="min-h-screen bg-[#f6f9fa] text-[#102a43]"><aside className="fixed inset-y-0 left-0 hidden w-72 border-r border-[#dce8eb] bg-white p-6 lg:block"><a href="/" className="text-xl font-bold">Raamed<span className="block text-xs font-normal text-[#6f8793]">Admin workspace</span></a><nav className="mt-12 grid gap-2">{nav.map((item) => <button key={item} onClick={() => setActive(item)} className={`rounded-xl px-4 py-3 text-left text-sm ${active === item ? 'bg-[#e5f4f2] font-semibold text-[#f36f2b]' : 'text-[#5a7484]'}`}>{item}</button>)}</nav></aside><section className="lg:pl-72"><header className="border-b border-[#dce8eb] bg-white px-5 py-5"><p className="text-sm text-[#6f8793]">Raamed operations</p><h1 className="text-2xl font-semibold">{active}</h1></header><div className="p-5 lg:p-8">{message && <p className="mb-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}
    {active === 'Overview' && <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[['All visitors', metrics.visitors], ['All quotes', metrics.quotes], ['Today', metrics.daily], ['This month', metrics.monthly], ['This year', metrics.yearly]].map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-[#dce8eb] bg-white p-5"><p className="text-sm text-[#6f8793]">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>)}</div><div className="mt-6 rounded-2xl border border-[#dce8eb] bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Recent quote enquiries</h2><button onClick={() => setActive('Leads & enquiries')} className="text-sm text-[#f36f2b]">View all</button></div><div className="mt-4 grid gap-3">{leads.slice(0, 5).map((lead, i) => <div key={i} className="flex justify-between border-b border-[#edf2f3] pb-3 text-sm"><span className="font-medium">{lead.name || 'Unnamed'}<span className="ml-2 text-[#6f8793]">{lead.organization}</span></span><span className="text-[#6f8793]">{lead.email}</span></div>)}{!leads.length && <p className="text-sm text-[#6f8793]">No enquiries yet.</p>}</div></div></>}
    {active === 'Products' && <div className="grid gap-6 lg:grid-cols-[380px_1fr]"><form onSubmit={saveProduct} className="rounded-2xl border border-[#dce8eb] bg-white p-5"><h2 className="font-semibold">Add product</h2><div className="mt-4 grid gap-3"><input required placeholder="Product name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="rounded-xl border p-3" /><select required={!newCategory} value={newCategory ? '__new__' : form.category} onChange={(e) => { if (e.target.value === '__new__') { setNewCategory(true); setForm({ ...form, category: '' }) } else setForm({ ...form, category: e.target.value }) }} className="rounded-xl border p-3"><option value="">Select category</option>{categories.map((c) => <option key={c}>{c}</option>)}<option value="__new__">+ New category</option></select>{newCategory && <input required placeholder="New category name" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className="rounded-xl border p-3" />}<textarea required placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="min-h-28 rounded-xl border p-3" /><input type="file" accept="image/*" onChange={async (e) => { const file = e.target.files?.[0]; if (file) setForm({ ...form, image: await upload(file) }) }} className="rounded-xl border border-dashed p-3" /><button className="rounded-xl bg-[#f36f2b] p-3 font-semibold text-white">Publish product</button></div></form><div className="grid gap-4 sm:grid-cols-2">{allProducts.map((product) => <article key={product._id || product.name} className="rounded-2xl border border-[#dce8eb] bg-white p-5">{product.image && <img src={product.image} alt={product.name} className="mb-4 h-32 w-full rounded-xl object-cover" />}<p className="text-xs font-semibold uppercase tracking-wider text-[#f36f2b]">{product.category}</p><h3 className="mt-2 font-semibold">{product.name}</h3><p className="mt-2 text-sm text-[#6f8793]">{product.description}</p><button type="button" onClick={() => removeProduct(product)} className="mt-4 w-full rounded-xl border border-red-200 px-3 py-2 text-sm font-semibold text-red-600 transition hover:bg-red-50">Delete product</button></article>)}</div></div>}
    {active === 'Leads & enquiries' && <div className="rounded-2xl border border-[#dce8eb] bg-white p-5"><div className="flex justify-between"><h2 className="font-semibold">All lead enquiries</h2><button onClick={() => window.print()} className="rounded-xl border px-4 py-2 text-sm">Print all leads</button></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-[#6f8793]"><th className="p-3">Name</th><th className="p-3">Email</th><th className="p-3">Phone</th><th className="p-3">Organization</th><th className="p-3">Message</th><th className="p-3">Date</th></tr></thead><tbody>{leads.map((l, i) => <tr key={i} className="border-b"><td className="p-3">{l.name}</td><td className="p-3">{l.email}</td><td className="p-3">{l.phone}</td><td className="p-3">{l.organization}</td><td className="max-w-xs p-3">{l.message}</td><td className="whitespace-nowrap p-3">{l.createdAt ? new Date(l.createdAt).toLocaleDateString() : '-'}</td></tr>)}</tbody></table></div></div>}
    {active === 'Analytics' && <div className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-[#dce8eb] bg-white p-5"><h2 className="font-semibold">Visitor and quote overview</h2><div className="mt-6 grid grid-cols-3 items-end gap-5"><div><div className="h-36 rounded-t-xl bg-[#e5f4f2]" style={{ height: `${Math.max(20, Math.min(144, metrics.yearly))}px` }} /><p className="mt-2 text-center text-xs">Year</p></div><div><div className="h-36 rounded-t-xl bg-[#b7ddd7]" style={{ height: `${Math.max(20, Math.min(144, metrics.monthly))}px` }} /><p className="mt-2 text-center text-xs">Month</p></div><div><div className="h-36 rounded-t-xl bg-[#f36f2b]" style={{ height: `${Math.max(20, Math.min(144, metrics.daily))}px` }} /><p className="mt-2 text-center text-xs">Today</p></div></div></div><div className="rounded-2xl border border-[#dce8eb] bg-white p-5"><h2 className="font-semibold">Product quote clicks</h2><div className="mt-5 grid gap-4">{metrics.products.map((p) => <div key={p.name}><div className="flex justify-between text-sm"><span>{p.name}</span><span>{p.clicks}</span></div><div className="mt-2 h-2 rounded-full bg-[#edf2f3]"><div className="h-2 rounded-full bg-[#f36f2b]" style={{ width: `${Math.min(100, p.clicks * 10)}%` }} /></div></div>)}{!metrics.products.length && <p className="text-sm text-[#6f8793]">Product click analytics will appear here as visitors interact with quotes.</p>}</div></div></div>}
    {active === 'Settings' && <div className="max-w-2xl rounded-2xl border border-[#dce8eb] bg-white p-6"><h2 className="text-xl font-semibold">Website settings</h2><p className="mt-1 text-sm text-[#6f8793]">Update the contact details shown across the public website.</p><form onSubmit={saveSettings} className="mt-6 grid gap-4"><label className="grid gap-2 text-sm font-medium">Phone<input value={settings.phone} onChange={(e) => setSettings({ ...settings, phone: e.target.value })} className="rounded-xl border p-3" placeholder="+91..." /></label><label className="grid gap-2 text-sm font-medium">WhatsApp<input value={settings.whatsapp} onChange={(e) => setSettings({ ...settings, whatsapp: e.target.value })} className="rounded-xl border p-3" placeholder="WhatsApp number" /></label><label className="grid gap-2 text-sm font-medium">Support email<input type="email" value={settings.email} onChange={(e) => setSettings({ ...settings, email: e.target.value })} className="rounded-xl border p-3" placeholder="Business@raamed.org" /></label><button className="rounded-xl bg-[#f36f2b] p-3 font-semibold text-white">Save website settings</button></form><div className="mt-8 border-t pt-6"><h3 className="font-semibold">Admin password</h3><p className="mt-1 text-sm text-[#6f8793]">Change the password from the secure admin credentials settings in Vercel.</p><a className="mt-3 inline-block text-sm font-semibold text-[#f36f2b]" href="https://vercel.com/raamed1/raamed-org-could-host/settings/environment-variables" target="_blank" rel="noreferrer">Open Vercel password settings</a></div></div>}
  </div></section></main>
}
