'use client'

import React, { createContext, useContext, useEffect, useState } from 'react'

export type Language = 'en' | 'es' | 'fr' | 'de' | 'ar' | 'zh' | 'ru' | 'ja' | 'pt' | 'hi' | 'bn' | 'ta' | 'mr'

export type LanguageOption = {
  code: Language
  name: string
  nativeName: string
  flag: string
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
]

const translations: Record<Language, Record<string, string>> = {
  en: {
    products: 'Products',
    viewAllEquipment: 'View all equipment',
    aboutUs: 'About us',
    branchNetwork: 'Branch network',
    customers: 'Customers',
    requestQuote: 'Request a quote',
    callUs: 'Call Us',
    talkToSpecialist: 'Talk to a specialist',
    exploreEquipment: 'Explore equipment',
    trustedPartners: 'Trusted clinical partners',
    heroTitle: 'The dependable standard for medical care.',
    heroSubtitle: 'We help hospitals, clinics, and care teams make confident equipment decisions—with practical expertise, responsive support, and technology that performs.',
    qualityChecked: 'Quality checked',
    regionalSupport: 'Regional support',
    equipmentDesk: 'The equipment desk',
    builtAroundCare: 'Built around the way care works.',
    seeFullCatalogue: 'See full catalogue',
    enquireAboutThis: 'Enquire about this',
    noEquipmentFound: 'No equipment currently listed in the catalogue.',
    betterHandover: 'A better handover',
    equipmentBeginning: 'Equipment is only the beginning.',
    handoverSubtitle: 'From product selection to installation and service, our team stays close to your workflow. Get a clear recommendation, transparent documentation, and support that answers.',
    insideClinicalSupport: 'Inside our clinical support',
    raamedInField: 'Raamed in the field',
    exploreRaamed: 'Explore Raamed',
    mediaCentre: 'Media centre',
    talkToTeam: 'Talk to our team',
    delhiHq: 'Delhi HQ',
    monSatHours: 'Mon–Sat, 9:00–18:00 IST',
    copyright: '© 2026 Raamed (RAAMED / RAMMED). Built for dependable medical care. All rights reserved.',
    patientMonitoring: 'Patient monitoring',
    surgicalSystems: 'Surgical systems',
    endoscopySystems: 'Endoscopy systems',
    respiratoryCare: 'Respiratory care',
    sterilizationReprocessing: 'Sterilization & reprocessing',
    selectLanguage: 'Select Language',
    translateWithGoogle: 'Auto-Translate Page',
    clinicalTechTag: 'Clinical technology / 2026',
    precisionCare: 'Precision at the point of care.',
    exploreClearerStandard: 'Explore a clearer standard for modern clinical environments.',
    thrMonitor: 'THR / MONITOR',
    liveReadyInterface: 'Live-ready interface',
    previewComingSoon: 'Preview coming soon',
    mediaDescription: 'A dedicated place for our clinical stories, equipment demonstrations, and team updates.',
    branchNetworkEyebrow: 'Branch Network & Offices',
    branchNetworkTitle: 'Headquartered in Delhi, serving healthcare teams across India.',
    branchNetworkSubtitle: 'Our Main Branch in Delhi and dedicated regional branches in Patna and Lucknow connect hospitals and clinics with rapid equipment delivery and responsive clinical support.',
    mainBranchHq: 'Main Branch (Headquarters)',
    patnaBranch: 'Patna Branch',
    lucknowBranch: 'Lucknow Branch',
    landlineHq: '(Landline HQ)',
    mobileWhatsapp: '(Mobile / WhatsApp)',
    openInGoogleMaps: 'Open in Google Maps',
    needDirectAssistance: 'Need direct assistance?',
    connectDirectly: 'Connect directly with our Main Branch or regional representatives.',
    quickTurnaroundText: 'We provide quick turnaround for clinical enquiries, product demos, and technical maintenance across Delhi, Bihar, and Uttar Pradesh.',
    callDelhiHqBtn: 'Call Delhi HQ: 011-36650267',
    emailBtn: 'Email: Business@raamed.online',
    aboutEyebrow: 'About Raamed',
    aboutTitle: 'A medical equipment partner built around clarity.',
    aboutSubtitle: 'Healthcare teams do not need more noise. They need equipment that fits their workflow, guidance they can trust, and support that stays close after delivery.',
    practicalExpertise: 'Practical expertise',
    practicalExpertiseText: 'Technical detail translated into confident clinical decisions.',
    humanSupport: 'Human support',
    humanSupportText: 'A responsive team from first enquiry through after-sales care.',
    longTermThinking: 'Long-term thinking',
    longTermThinkingText: 'Partnerships designed around reliability, training, and uptime.',
    peopleBehindTitle: 'Our people behind the partnership',
    prepareDeliveryTitle: 'How we prepare every delivery',
    customersEyebrow: 'Customers',
    customersTitle: 'Trusted by teams who keep care moving.',
    customersSubtitle: 'Doctors, hospitals, clinics, and procurement teams choose Raamed for dependable equipment and support that stays close to the work.',
    workWithRaamed: 'Work with Raamed',
    planningNewDepartment: 'Planning a new department, procedure room, or equipment refresh?',
    talkToOurTeam: 'Talk to our team',
    mediaEyebrow: 'Media centre',
    mediaTitle: 'A closer look at how better care comes together.',
    mediaSubtitle: 'Explore our photo stories, product demonstrations, office updates, and clinical conversations.',
    reviewsEyebrow: 'Reviews',
    reviewsTitle: 'Trusted by the people behind care.',
    reviewsSubtitle: 'The best measure of our work is what clinical and procurement teams say after they have worked with us.',
    catalogueEyebrow: 'Equipment catalogue',
    catalogueTitle: 'Equipment selected for real clinical work.',
    catalogueSubtitle: "Explore Raamed's equipment categories. Tell us what your team is planning and we'll help you find the right fit.",
    allEquipment: 'All equipment',
    discussThisRange: 'Discuss this range',
  },
  es: {
    products: 'Productos',
    viewAllEquipment: 'Ver todo el equipamiento',
    aboutUs: 'Nosotros',
    branchNetwork: 'Red de sucursales',
    customers: 'Clientes',
    requestQuote: 'Solicitar presupuesto',
    callUs: 'Llámanos',
    talkToSpecialist: 'Hablar con un especialista',
    exploreEquipment: 'Explorar equipamiento',
    trustedPartners: 'Socios clínicos de confianza',
    heroTitle: 'El estándar confiable para la atención médica.',
    heroSubtitle: 'Ayudamos a hospitales y clínicas a tomar decisiones de equipamiento seguras con experiencia práctica y soporte responsivo.',
    qualityChecked: 'Calidad verificada',
    regionalSupport: 'Soporte regional',
    equipmentDesk: 'Mesa de equipamiento',
    builtAroundCare: 'Diseñado en torno al trabajo clínico.',
    seeFullCatalogue: 'Ver catálogo completo',
    enquireAboutThis: 'Consultar sobre esto',
    noEquipmentFound: 'No hay equipamiento catalogado actualmente.',
    betterHandover: 'Una mejor entrega',
    equipmentBeginning: 'El equipo es solo el comienzo.',
    handoverSubtitle: 'Desde la selección hasta la instalación y servicio, nuestro equipo acompaña su flujo de trabajo.',
    insideClinicalSupport: 'Soporte clínico',
    raamedInField: 'Raamed en el campo',
    exploreRaamed: 'Explorar Raamed',
    mediaCentre: 'Centro de medios',
    talkToTeam: 'Hablar con nuestro equipo',
    delhiHq: 'Sede en Delhi',
    monSatHours: 'Lun–Sáb, 9:00–18:00 IST',
    copyright: '© 2026 Raamed. Todos los derechos reservados.',
    patientMonitoring: 'Monitoreo de pacientes',
    surgicalSystems: 'Sistemas quirúrgicos',
    endoscopySystems: 'Sistemas de endoscopia',
    respiratoryCare: 'Cuidado respiratorio',
    sterilizationReprocessing: 'Esterilización y reprocesamiento',
    selectLanguage: 'Seleccionar idioma',
    translateWithGoogle: 'Traducción automática',
    clinicalTechTag: 'Tecnología clínica / 2026',
    precisionCare: 'Precisión en el punto de atención.',
    exploreClearerStandard: 'Explore un estándar más claro para entornos clínicos modernos.',
    thrMonitor: 'MONITOR / THR',
    liveReadyInterface: 'Interfaz lista en vivo',
    yearsExpText: 'Años de experiencia clínica',
    keyBranchesText: 'Sucursales clave en la India (Sede en Delhi)',
    responseWindowText: 'Ventana de respuesta típica',
    checkBackLater: 'Vuelva a consultar más tarde o contáctenos directamente.',
    raamedDescription: 'Raamed – Equipamiento médico confiable y soporte en India.',
    previewComingSoon: 'Vista previa pronto',
    mediaDescription: 'Un lugar dedicado a nuestras historias clínicas y novedades.',
    branchNetworkEyebrow: 'Red de Sucursales y Oficinas',
    branchNetworkTitle: 'Sede central en Delhi, servicio en toda la India.',
    branchNetworkSubtitle: 'Nuestra sede principal en Delhi y sucursales en Patna y Lucknow conectan clínicas con entregas rápidas.',
    mainBranchHq: 'Sede Principal (Headquarters)',
    patnaBranch: 'Sucursal Patna',
    lucknowBranch: 'Sucursal Lucknow',
    landlineHq: '(Teléfono Fijo HQ)',
    mobileWhatsapp: '(Móvil / WhatsApp)',
    openInGoogleMaps: 'Abrir en Google Maps',
    needDirectAssistance: '¿Necesita asistencia directa?',
    connectDirectly: 'Conéctese directamente con nuestra sede central o representantes.',
    quickTurnaroundText: 'Brindamos respuesta rápida para consultas clínicas y mantenimiento técnico.',
    callDelhiHqBtn: 'Llamar a Sede Delhi: 011-36650267',
    emailBtn: 'Email: Business@raamed.online',
    aboutEyebrow: 'Sobre Raamed',
    aboutTitle: 'Un socio de equipamiento médico basado en la claridad.',
    aboutSubtitle: 'Las instituciones médicas necesitan equipos confiables y soporte cercano.',
    practicalExpertise: 'Experiencia práctica',
    practicalExpertiseText: 'Detalles técnicos traducidos en decisiones clínicas seguras.',
    humanSupport: 'Soporte humano',
    humanSupportText: 'Un equipo receptivo desde la primera consulta.',
    longTermThinking: 'Visión a largo plazo',
    longTermThinkingText: 'Relaciones basadas en la confiabilidad y disponibilidad.',
    peopleBehindTitle: 'Nuestro equipo tras la alianza',
    prepareDeliveryTitle: 'Cómo preparamos cada entrega',
    customersEyebrow: 'Clientes',
    customersTitle: 'La confianza de quienes cuentan con nosotros.',
    customersSubtitle: 'Médicos y hospitales eligen Raamed por su equipamiento de confianza.',
    workWithRaamed: 'Trabaje con Raamed',
    planningNewDepartment: '¿Planea un nuevo departamento o renovación de equipos?',
    talkToOurTeam: 'Hablar con nuestro equipo',
    mediaEyebrow: 'Centro de Medios',
    mediaTitle: 'Una mirada cercana a nuestro trabajo.',
    mediaSubtitle: 'Explore historias fotográficas, demostraciones de productos y noticias.',
    reviewsEyebrow: 'Reseñas',
    reviewsTitle: 'Confiado por profesionales de la salud.',
    reviewsSubtitle: 'La mejor medida de nuestro trabajo es la opinión de nuestros clientes.',
    catalogueEyebrow: 'Catálogo de Equipamiento',
    catalogueTitle: 'Equipamiento seleccionado para el trabajo clínico real.',
    catalogueSubtitle: 'Explore las categorías de equipos y encuentre la solución adecuada.',
    allEquipment: 'Todo el equipamiento',
    discussThisRange: 'Consultar esta línea',
  },
  fr: {
    products: 'Produits',
    viewAllEquipment: 'Voir tout équipement',
    aboutUs: 'À propos de nous',
    branchNetwork: 'Réseau de succursales',
    customers: 'Clients',
    requestQuote: 'Demander un devis',
    callUs: 'Appelez-nous',
    talkToSpecialist: 'Parler à un spécialiste',
    exploreEquipment: 'Explorer les équipements',
    trustedPartners: 'Partenaires cliniques de confiance',
    heroTitle: 'La norme fiable pour les soins médicaux.',
    heroSubtitle: 'Nous aidons les hôpitaux et cliniques à prendre des décisions d’équipement éclairées.',
    qualityChecked: 'Qualité vérifiée',
    regionalSupport: 'Support régional',
    equipmentDesk: 'Bureau des équipements',
    builtAroundCare: 'Conçu pour le travail clinique.',
    seeFullCatalogue: 'Voir le catalogue complet',
    enquireAboutThis: 'Se renseigner sur ce produit',
    noEquipmentFound: 'Aucun équipement actuellement répertorié.',
    betterHandover: 'Un meilleur accompagnement',
    equipmentBeginning: 'L’équipement n’est que le début.',
    handoverSubtitle: 'De la sélection à l’installation et au service, notre équipe reste proche de vous.',
    insideClinicalSupport: 'Notre support clinique',
    raamedInField: 'Raamed sur le terrain',
    exploreRaamed: 'Explorer Raamed',
    mediaCentre: 'Centre média',
    talkToTeam: 'Parler à notre équipe',
    delhiHq: 'Siège social à Delhi',
    monSatHours: 'Lun–Sam, 9h00–18h00 IST',
    copyright: '© 2026 Raamed. Tous droits réservés.',
    patientMonitoring: 'Surveillance des patients',
    surgicalSystems: 'Systèmes chirurgicaux',
    endoscopySystems: 'Systèmes d’endoscopie',
    respiratoryCare: 'Soins respiratoires',
    sterilizationReprocessing: 'Stérilisation & retraitement',
    selectLanguage: 'Choisir la langue',
    translateWithGoogle: 'Traduction automatique',
    clinicalTechTag: 'Technologie clinique / 2026',
    precisionCare: 'Précision au point d’intervention.',
    exploreClearerStandard: 'Explorez une norme plus claire pour les environnements cliniques.',
    thrMonitor: 'MONITEUR / THR',
    liveReadyInterface: 'Interface prête en direct',
    yearsExpText: 'Années d’expérience clinique',
    keyBranchesText: 'Principales succursales en Inde (Siège à Delhi)',
    responseWindowText: 'Délai de réponse habituel',
    checkBackLater: 'Revenez plus tard ou contactez-nous directement.',
    raamedDescription: 'Raamed – Équipements médicaux fiables et support en Inde.',
    previewComingSoon: 'Aperçu bientôt disponible',
    mediaDescription: 'Un espace dédié à nos démonstrations et actualités.',
    branchNetworkEyebrow: 'Réseau de Succursales & Bureaux',
    branchNetworkTitle: 'Siège à Delhi, service dans toute l’Inde.',
    branchNetworkSubtitle: 'Notre siège principal à Delhi et nos succursales régionales garantissent une livraison rapide.',
    mainBranchHq: 'Branche Principale (Siège Social)',
    patnaBranch: 'Branche de Patna',
    lucknowBranch: 'Branche de Lucknow',
    landlineHq: '(Ligne Fixe HQ)',
    mobileWhatsapp: '(Mobile / WhatsApp)',
    openInGoogleMaps: 'Ouvrir dans Google Maps',
    needDirectAssistance: 'Besoin d’assistance directe ?',
    connectDirectly: 'Contactez directement notre siège ou nos représentants.',
    quickTurnaroundText: 'Nous assurons un traitement rapide pour les demandes médicales et la maintenance.',
    callDelhiHqBtn: 'Appeler le Siège de Delhi : 011-36650267',
    emailBtn: 'E-mail : Business@raamed.online',
    aboutEyebrow: 'À propos de Raamed',
    aboutTitle: 'Un partenaire d’équipement médical axé sur la clarté.',
    aboutSubtitle: 'Les équipes médicales ont besoin d’équipements adaptés et d’un accompagnement durable.',
    practicalExpertise: 'Expertise pratique',
    practicalExpertiseText: 'Des détails techniques traduits en décisions cliniques sûres.',
    humanSupport: 'Support humain',
    humanSupportText: 'Une équipe réactive de la demande initiale au service après-vente.',
    longTermThinking: 'Vision à long terme',
    longTermThinkingText: 'Des partenariats conçus autour de la fiabilité.',
    peopleBehindTitle: 'Notre équipe derrière le partenariat',
    prepareDeliveryTitle: 'Comment nous préparons chaque livraison',
    customersEyebrow: 'Clients',
    customersTitle: 'La confiance des équipes soignantes.',
    customersSubtitle: 'Médecins et hôpitaux choisissent Raamed pour des équipements fiables.',
    workWithRaamed: 'Travailler avec Raamed',
    planningNewDepartment: 'Vous planifiez un nouveau service ou le renouvellement d’équipements ?',
    talkToOurTeam: 'Parler à notre équipe',
    mediaEyebrow: 'Centre Média',
    mediaTitle: 'Découvrez les coulisses de notre accompagnement.',
    mediaSubtitle: 'Explorez nos reportages photo, démonstrations et actualités.',
    reviewsEyebrow: 'Avis clients',
    reviewsTitle: 'La confiance des professionnels de santé.',
    reviewsSubtitle: 'La meilleure mesure de notre travail réside dans les témoignages de nos clients.',
    catalogueEyebrow: 'Catalogue d’Équipements',
    catalogueTitle: 'Équipements sélectionnés pour la pratique clinique réelle.',
    catalogueSubtitle: 'Explorez les catégories d’équipements Raamed et trouvez la solution idéale.',
    allEquipment: 'Tous les équipements',
    discussThisRange: 'Discuter de cette gamme',
  },
  de: {
    products: 'Produkte',
    viewAllEquipment: 'Alle Geräte anzeigen',
    aboutUs: 'Über uns',
    branchNetwork: 'Filialnetzwerk',
    customers: 'Kunden',
    requestQuote: 'Angebot anfordern',
    callUs: 'Rufen Sie uns an',
    talkToSpecialist: 'Mit einem Spezialisten sprechen',
    exploreEquipment: 'Geräte entdecken',
    trustedPartners: 'Vertrauenswürdige klinische Partner',
    heroTitle: 'Der zuverlässige Standard für medizinische Versorgung.',
    heroSubtitle: 'Wir unterstützen Krankenhäuser und Kliniken bei der Auswahl erstklassiger medizinischer Geräte.',
    qualityChecked: 'Geprüfte Qualität',
    regionalSupport: 'Regionaler Support',
    equipmentDesk: 'Geräte-Desk',
    builtAroundCare: 'Entwickelt für den klinischen Alltag.',
    seeFullCatalogue: 'Vollständigen Katalog anzeigen',
    enquireAboutThis: 'Anfrage zu diesem Produkt',
    noEquipmentFound: 'Derzeit keine Geräte im Katalog.',
    betterHandover: 'Bessere Übergabe',
    equipmentBeginning: 'Die Ausrüstung ist erst der Anfang.',
    handoverSubtitle: 'Von der Produktauswahl bis zur Installation begleiten wir Ihre Arbeitsabläufe.',
    insideClinicalSupport: 'Klinischer Support',
    raamedInField: 'Raamed im Einsatz',
    exploreRaamed: 'Raamed entdecken',
    mediaCentre: 'Medienzentrum',
    talkToTeam: 'Mit unserem Team sprechen',
    delhiHq: 'Zentrale in Delhi',
    monSatHours: 'Mo–Sa, 9:00–18:00 IST',
    copyright: '© 2026 Raamed. Alle Rechte vorbehalten.',
    patientMonitoring: 'Patientenüberwachung',
    surgicalSystems: 'Chirurgische Systeme',
    endoscopySystems: 'Endoskopie-Systeme',
    respiratoryCare: 'Beatmung & Atemtherapie',
    sterilizationReprocessing: 'Sterilisation & Aufbereitung',
    selectLanguage: 'Sprache wählen',
    translateWithGoogle: 'Automatische Übersetzung',
    clinicalTechTag: 'Klinische Technologie / 2026',
    precisionCare: 'Präzision am Behandlungspunkt.',
    exploreClearerStandard: 'Entdecken Sie einen klaren Standard für klinische Umgebungen.',
    thrMonitor: 'MONITOR / THR',
    liveReadyInterface: 'Live-Schnittstelle',
    yearsExpText: 'Jahre klinische Erfahrung',
    keyBranchesText: 'Wichtige Filialen in Indien (Zentrale in Delhi)',
    responseWindowText: 'Typisches Antwortzeitfenster',
    checkBackLater: 'Schauen Sie später vorbei oder kontaktieren Sie uns direkt.',
    raamedDescription: 'Raamed – Zuverlässige Medizinprodukte und Support in Indien.',
    previewComingSoon: 'Vorschau demnächst',
    mediaDescription: 'Ein Ort für klinische Berichte und Team-Updates.',
    branchNetworkEyebrow: 'Filialnetzwerk & Standorte',
    branchNetworkTitle: 'Hauptsitz in Delhi, bundesweiter Service in Indien.',
    branchNetworkSubtitle: 'Unser Hauptsitz in Delhi und regionale Filialen verbinden Kliniken mit schneller Lieferung.',
    mainBranchHq: 'Hauptfiliale (Zentrale)',
    patnaBranch: 'Filiale Patna',
    lucknowBranch: 'Filiale Lucknow',
    landlineHq: '(Festnetz HQ)',
    mobileWhatsapp: '(Mobil / WhatsApp)',
    openInGoogleMaps: 'In Google Maps öffnen',
    needDirectAssistance: 'Benötigen Sie direkte Unterstützung?',
    connectDirectly: 'Wenden Sie sich direkt an unseren Hauptsitz oder Vertreter.',
    quickTurnaroundText: 'Wir bieten schnelle Reaktionszeiten für Anfragen und Wartung.',
    callDelhiHqBtn: 'Zentrale Delhi anrufen: 011-36650267',
    emailBtn: 'E-Mail: Business@raamed.online',
    aboutEyebrow: 'Über Raamed',
    aboutTitle: 'Ihr Medizintechnik-Partner mit klarer Haltung.',
    aboutSubtitle: 'Medizinisches Personal benötigt verlässliche Geräte und verlässlichen Service.',
    practicalExpertise: 'Praktische Expertise',
    practicalExpertiseText: 'Technische Details verständlich für sichere klinische Entscheidungen.',
    humanSupport: 'Persönlicher Support',
    humanSupportText: 'Ein engagiertes Team von der Anfrage bis zum Kundendienst.',
    longTermThinking: 'Langfristiges Denken',
    longTermThinkingText: 'Partnerschaften ausgerichtet auf Zuverlässigkeit und Betriebsbereitschaft.',
    peopleBehindTitle: 'Unser Team hinter der Partnerschaft',
    prepareDeliveryTitle: 'Wie wir jede Lieferung vorbereiten',
    customersEyebrow: 'Kunden',
    customersTitle: 'Vertraut von führenden medizinischen Teams.',
    customersSubtitle: 'Ärzte und Kliniken wählen Raamed für zuverlässige Medizintechnik.',
    workWithRaamed: 'Mit Raamed zusammenarbeiten',
    planningNewDepartment: 'Planen Sie eine neue Abteilung oder eine Geräteerneuerung?',
    talkToOurTeam: 'Mit unserem Team sprechen',
    mediaEyebrow: 'Medienzentrum',
    mediaTitle: 'Ein genauerer Blick auf unsere Arbeit.',
    mediaSubtitle: 'Entdecken Sie Fotostories, Produktdemonstrationen und Berichte.',
    reviewsEyebrow: 'Bewertungen',
    reviewsTitle: 'Geschätzt von Experten im Gesundheitswesen.',
    reviewsSubtitle: 'Unser Erfolg bemisst sich an der Zufriedenheit unserer Kunden.',
    catalogueEyebrow: 'Gerätekatalog',
    catalogueTitle: 'Ausgewählte Ausrüstung für die klinische Praxis.',
    catalogueSubtitle: 'Entdecken Sie die Kategorien und finden Sie die passende Lösung.',
    allEquipment: 'Alle Geräte',
    discussThisRange: 'Diese Produktreihe besprechen',
  },
  ar: {
    products: 'المنتجات',
    viewAllEquipment: 'عرض جميع المعدات',
    aboutUs: 'من نحن',
    branchNetwork: 'شبكة الفروع',
    customers: 'العملاء',
    requestQuote: 'طلب عرض سعر',
    callUs: 'اتصل بنا',
    talkToSpecialist: 'تحدث مع متخصص',
    exploreEquipment: 'استكشاف المعدات',
    trustedPartners: 'شركاء طبيون موثوقون',
    heroTitle: 'المعيار الموثوق للرعاية الطبية.',
    heroSubtitle: 'نساعد المستشفيات والعيادات على اتخاذ قرارات معدات بثقة مع دعم فني متكامل.',
    qualityChecked: 'جودة معتمدة',
    regionalSupport: 'دعم إقليمي',
    equipmentDesk: 'منصة المعدات',
    builtAroundCare: 'مصمم حول متطلبات الرعاية الصحية.',
    seeFullCatalogue: 'عرض الكتالوج الكامل',
    enquireAboutThis: 'استفسر عن هذا المنتج',
    noEquipmentFound: 'لا توجد معدات حالياً في الكتالوج.',
    betterHandover: 'تسليم وخدمة أفضل',
    equipmentBeginning: 'المعدات هي مجرد البداية.',
    handoverSubtitle: 'من اختيار المنتج إلى التركيب والصيانة، فريقنا دائمًا بجانبك.',
    insideClinicalSupport: 'الدعم الطبي المتخصص',
    raamedInField: 'راميد في الميدان',
    exploreRaamed: 'استكشف راميد',
    mediaCentre: 'المركز الإعلامي',
    talkToTeam: 'تحدث مع فريقنا',
    delhiHq: 'المقر الرئيسي بدلهي',
    monSatHours: 'الإثنين–السبت، 9:00–18:00 بتوقيت الهند',
    copyright: '© 2026 راميد. جميع الحقوق محفوظة.',
    patientMonitoring: 'مراقبة المرضى',
    surgicalSystems: 'الأنظمة الجراحية',
    endoscopySystems: 'أنظمة المناظير',
    respiratoryCare: 'رعاية الجهاز التنفسي',
    sterilizationReprocessing: 'التعقيم وإعادة المعالجة',
    selectLanguage: 'اختر اللغة',
    translateWithGoogle: 'ترجمة فورية للموقع',
    clinicalTechTag: 'التكنولوجيا الطبية / 2026',
    precisionCare: 'الدقة في نقطة الرعاية الطبية.',
    exploreClearerStandard: 'استكشف معياراً أكثر وضوحاً للبيئات الطبية الحديثة.',
    thrMonitor: 'شاشة المراقبة / THR',
    liveReadyInterface: 'واجهة جاهزة للبث المباشر',
    yearsExpText: 'سنوات من الخبرة الطبية',
    keyBranchesText: 'فروع رئيسية عبر الهند (المقر الرئيسي بدلهي)',
    responseWindowText: 'متوسط زمن الاستجابة',
    checkBackLater: 'تفقّد الكتالوج لاحقاً أو اتصل بنا مباشرة.',
    raamedDescription: 'راميد – معدات طبية موثوقة ودعم فني في جميع أنحاء الهند.',
    previewComingSoon: 'المعاينة قريباً',
    mediaDescription: 'مكان مخصص لقصصنا الطبية وتحديثات الفريق.',
    branchNetworkEyebrow: 'شبكة الفروع والمكاتب',
    branchNetworkTitle: 'المقر الرئيسي بدلهي، وخدمات تمتد عبر الهند.',
    branchNetworkSubtitle: 'فرعنا الرئيسي بدلهي وفروعنا في باتنا ولخناو توفر توريداً سريعاً ودعماً طبياً.',
    mainBranchHq: 'الفرع الرئيسي (المقر الرئيسي)',
    patnaBranch: 'فرع باتنا',
    lucknowBranch: 'فرع لخناو',
    landlineHq: '(الهاتف الثابت دلهي)',
    mobileWhatsapp: '(الجوال / واتساب)',
    openInGoogleMaps: 'فتح في خرائط جوجل',
    needDirectAssistance: 'هل تحتاج إلى مساعدة مباشرة؟',
    connectDirectly: 'تواصل مباشرة مع مقرنا الرئيسي أو ممثلينا.',
    quickTurnaroundText: 'نوفر استجابة سريعة للاستفسارات الطبية والصيانة.',
    callDelhiHqBtn: 'الاتصال بمقر دلهي: 011-36650267',
    emailBtn: 'البريد: Business@raamed.online',
    aboutEyebrow: 'عن راميد',
    aboutTitle: 'شريك الأجهزة الطبية القائم على الوضوح والثقة.',
    aboutSubtitle: 'تحتاج الفرق الطبية إلى معدات موثوقة ودعم مستمر.',
    practicalExpertise: 'خبرة عملية',
    practicalExpertiseText: 'تفاصيل تقنية مترجمة إلى قرارات طبية واثقة.',
    humanSupport: 'دعم بشري',
    humanSupportText: 'فريق متخصص من أول استفسار وحتى ما بعد البيع.',
    longTermThinking: 'رؤية طويلة الأجل',
    longTermThinkingText: 'شراكات قائمة على الموثوقية واستمرارية العمل.',
    peopleBehindTitle: 'فريقنا خلف هذه الشراكة',
    prepareDeliveryTitle: 'كيف نجهز كل عملية تسليم',
    customersEyebrow: 'عملاؤنا',
    customersTitle: 'ثقة الفرق التي ترعى المرضى.',
    customersSubtitle: 'يختار الأطباء والمستشفيات راميد للحصول على معدات موثوقة.',
    workWithRaamed: 'عمل مع راميد',
    planningNewDepartment: 'هل تخطط لافتتاح قسم جديد أو تحديث المعدات؟',
    talkToOurTeam: 'تحدث مع فريقنا',
    mediaEyebrow: 'المركز الإعلامي',
    mediaTitle: 'نظرة أقرب على كيفية تقديم أفضل رعاية.',
    mediaSubtitle: 'استكشف القصص المصورة وعروض المنتجات وتحديثات الفريق.',
    reviewsEyebrow: 'التقييمات',
    reviewsTitle: 'محط ثقة المتخصصين في الرعاية الصحية.',
    reviewsSubtitle: 'المقياس الحقيقي لعملنا هو رأي عملائنا.',
    catalogueEyebrow: 'كتالوج المعدات',
    catalogueTitle: 'معدات مختارة للعمل الطبي الفعلي.',
    catalogueSubtitle: 'استكشف فئات المعدات لدى راميد واعثر على الخيار المناسب.',
    allEquipment: 'جميع المعدات',
    discussThisRange: 'ناقش هذه المجموعة',
  },
  zh: {
    products: '产品系列',
    viewAllEquipment: '查看所有设备',
    aboutUs: '关于我们',
    branchNetwork: '分支机构',
    customers: '合作客户',
    requestQuote: '获取报价',
    callUs: '联系我们',
    talkToSpecialist: '咨询专家',
    exploreEquipment: '浏览医疗设备',
    trustedPartners: '值得信赖的医疗合作伙伴',
    heroTitle: '医疗护理的可靠标准。',
    heroSubtitle: '我们以专业的知识和快速的响应，协助医院与诊所做出自信的设备选择。',
    qualityChecked: '质量严格把关',
    regionalSupport: '区域服务支持',
    equipmentDesk: '设备控制台',
    builtAroundCare: '围绕临床工作流设计。',
    seeFullCatalogue: '查看完整目录',
    enquireAboutThis: '咨询此产品',
    noEquipmentFound: '目前产品目录中无设备。',
    betterHandover: '卓越的交付与服务',
    equipmentBeginning: '提供设备只是合作的开始。',
    handoverSubtitle: '从设备选型到安装维护，我们的团队全程紧密配合您的工作流程。',
    insideClinicalSupport: '临床技术支持',
    raamedInField: 'Raamed 在一线',
    exploreRaamed: '探索 Raamed',
    mediaCentre: '新闻中心',
    talkToTeam: '联系我们的团队',
    delhiHq: '德里总部',
    monSatHours: '周一至周六，9:00–18:00 IST',
    copyright: '© 2026 Raamed。保留所有权利。',
    patientMonitoring: '病人监护系统',
    surgicalSystems: '手术室系统',
    endoscopySystems: '内窥镜诊断系统',
    respiratoryCare: '呼吸重症护理',
    sterilizationReprocessing: '消毒与再处理',
    selectLanguage: '选择语言',
    translateWithGoogle: '页面自动翻译',
    clinicalTechTag: '临床医疗技术 / 2026',
    precisionCare: '在护理诊断点精准呈现。',
    exploreClearerStandard: '探索现代临床环境的更高标准。',
    thrMonitor: '监护系统 / THR',
    liveReadyInterface: '实时就绪界面',
    yearsExpText: '年临床服务经验',
    keyBranchesText: '全印度主要分支机构（德里总部）',
    responseWindowText: '标准响应时间',
    checkBackLater: '请稍后再试或直接联系我们进行设备咨询。',
    raamedDescription: 'Raamed – 全印度医院与诊所值得信赖的医疗设备供应商。',
    previewComingSoon: '预览即将推出',
    mediaDescription: '专为我们的临床案例、设备演示和团队动态打造的空间。',
    branchNetworkEyebrow: '分支机构与办事处',
    branchNetworkTitle: '总部位于德里，服务覆盖全印度医疗团队。',
    branchNetworkSubtitle: '我们在德里的总公司以及巴特那和勒克瑙的区域分公司，确保设备快速交付与售后响应。',
    mainBranchHq: '总公司（总部）',
    patnaBranch: '巴特那分公司',
    lucknowBranch: '勒克瑙分公司',
    landlineHq: '（总部座机）',
    mobileWhatsapp: '（手机 / WhatsApp）',
    openInGoogleMaps: '在谷歌地图中打开',
    needDirectAssistance: '需要直接协助？',
    connectDirectly: '请直接联系我们的德里总部或区域代表。',
    quickTurnaroundText: '我们为全印度的设备咨询、产品演示和技术维护提供快速响应。',
    callDelhiHqBtn: '致电德里总部：011-36650267',
    emailBtn: '电子邮箱：Business@raamed.online',
    aboutEyebrow: '关于 Raamed',
    aboutTitle: '基于透明与专业的医疗设备合作伙伴。',
    aboutSubtitle: '医疗团队需要符合工作流程的可靠设备和全天候的售后支持。',
    practicalExpertise: '实用专业知识',
    practicalExpertiseText: '将复杂技术细节转化为可信赖的临床决策。',
    humanSupport: '贴心的人性化服务',
    humanSupportText: '从首次咨询到售后维护的全程响应团队。',
    longTermThinking: '长期合作理念',
    longTermThinkingText: '围绕高可靠性、培训和稳定运行建立合作关系。',
    peopleBehindTitle: '合作背后的团队团队',
    prepareDeliveryTitle: '我们如何准备每一次交付',
    customersEyebrow: '合作客户',
    customersTitle: '深受一线医疗团队信赖。',
    customersSubtitle: '医生、医院和采购团队选择 Raamed 作为长期设备供应商。',
    workWithRaamed: '与 Raamed 合作',
    planningNewDepartment: '正计划建立新科室、手术室或更新医疗设备？',
    talkToOurTeam: '联系我们的团队',
    mediaEyebrow: '新闻与媒体中心',
    mediaTitle: '近距离了解优质医疗护理的诞生。',
    mediaSubtitle: '探索图片故事、产品演示、办事处动态和临床访谈。',
    reviewsEyebrow: '客户评价',
    reviewsTitle: '深受医疗专业人员信赖。',
    reviewsSubtitle: '衡量我们工作成果的最佳标准，就是客户与我们合作后的评价。',
    catalogueEyebrow: '设备产品目录',
    catalogueTitle: '精选用于真实临床工作的医疗设备。',
    catalogueSubtitle: '浏览 Raamed 的设备类别，告知您的需求，我们将帮您找到最佳方案。',
    allEquipment: '所有设备',
    discussThisRange: '咨询该系列产品',
  },
  ru: {
    products: 'Продукция',
    viewAllEquipment: 'Посмотреть всё оборудование',
    aboutUs: 'О нас',
    branchNetwork: 'Сеть филиалов',
    customers: 'Клиенты',
    requestQuote: 'Запросить КП',
    callUs: 'Позвонить нам',
    talkToSpecialist: 'Связаться со специалистом',
    exploreEquipment: 'Каталог оборудования',
    trustedPartners: 'Надежные медицинские партнеры',
    heroTitle: 'Надежный стандарт медицинского обслуживания.',
    heroSubtitle: 'Помогаем больницам и клиникам принимать уверенные решения по оснащению оборудованием.',
    qualityChecked: 'Проверено по качеству',
    regionalSupport: 'Региональная поддержка',
    equipmentDesk: 'Каталог техники',
    builtAroundCare: 'Создано для эффективной работы.',
    seeFullCatalogue: 'Посмотреть полный каталог',
    enquireAboutThis: 'Запросить информацию',
    noEquipmentFound: 'В каталоге пока нет оборудования.',
    betterHandover: 'Качественный сервис и ввод в эксплуатацию',
    equipmentBeginning: 'Оборудование — это только начало.',
    handoverSubtitle: 'От выбора техники до монтажа и сервиса наш коллектив всегда на связи.',
    insideClinicalSupport: 'Клиническая поддержка',
    raamedInField: 'Raamed в работе',
    exploreRaamed: 'Узнать больше о Raamed',
    mediaCentre: 'Медиа-центр',
    talkToTeam: 'Связаться с командой',
    delhiHq: 'Головной офис в Дели',
    monSatHours: 'Пн–Сб, 9:00–18:00 IST',
    copyright: '© 2026 Raamed. Все права защищены.',
    patientMonitoring: 'Мониторинг пациентов',
    surgicalSystems: 'Хирургические системы',
    endoscopySystems: 'Эндоскопия',
    respiratoryCare: 'Респираторная поддержка',
    sterilizationReprocessing: 'Стерилизация и дезинфекция',
    selectLanguage: 'Выберите язык',
    translateWithGoogle: 'Автоматический перевод',
    clinicalTechTag: 'Медицинские технологии / 2026',
    precisionCare: 'Точность в точке оказания помощи.',
    exploreClearerStandard: 'Откройте для себя стандарт для современных клиник.',
    thrMonitor: 'МОНИТОР / THR',
    liveReadyInterface: 'Готовый интерфейс',
    yearsExpText: 'Лет клинического опыта',
    keyBranchesText: 'Ключевые филиалы по Индии (Головной офис в Дели)',
    responseWindowText: 'Стандартное время ответа',
    checkBackLater: 'Зайдите позже или свяжитесь с нами напрямую.',
    raamedDescription: 'Raamed – Надежное медицинское оборудование и поддержка.',
    previewComingSoon: 'Скоро в эфире',
    mediaDescription: 'Раздел для клинических историй и новостей.',
    branchNetworkEyebrow: 'Сеть филиалов и офисы',
    branchNetworkTitle: 'Головной офис в Дели, обслуживание по всей Индии.',
    branchNetworkSubtitle: 'Наш головной офис в Дели и филиалы в Патне и Лакхнау обеспечивают оперативную доставку оборудования.',
    mainBranchHq: 'Главный филиал (Головной офис)',
    patnaBranch: 'Филиал в Патне',
    lucknowBranch: 'Филиал в Лакхнау',
    landlineHq: '(Городской HQ)',
    mobileWhatsapp: '(Мобильный / WhatsApp)',
    openInGoogleMaps: 'Открыть в Google Картах',
    needDirectAssistance: 'Нужна прямая помощь?',
    connectDirectly: 'Свяжитесь напрямую с нашим головным офисом или представителями.',
    quickTurnaroundText: 'Мы обеспечиваем быстрое решение клинических запросов, демонстрацию техники и обслуживание.',
    callDelhiHqBtn: 'Позвонить в Дели HQ: 011-36650267',
    emailBtn: 'Email: Business@raamed.online',
    aboutEyebrow: 'О компании Raamed',
    aboutTitle: 'Надежный партнер в сфере медицинского оборудования.',
    aboutSubtitle: 'Медицинским организациям нужно оборудование, соответствующее их процессам, и надежная поддержка.',
    practicalExpertise: 'Практический опыт',
    practicalExpertiseText: 'Технические детали, превращенные в уверенные решения.',
    humanSupport: 'Персональная поддержка',
    humanSupportText: 'Ответственная команда от первого запроса до сервисного обслуживания.',
    longTermThinking: 'Долгосрочный подход',
    longTermThinkingText: 'Партнерство, ориентированное на надежность и бесперебойную работу.',
    peopleBehindTitle: 'Наша команда',
    prepareDeliveryTitle: 'Как мы готовим каждую поставку',
    customersEyebrow: 'Наши клиенты',
    customersTitle: 'Нам доверяют профессионалы.',
    customersSubtitle: 'Врачи, клиники и отделы закупок выбирают Raamed за надежное оборудование.',
    workWithRaamed: 'Сотрудничество с Raamed',
    planningNewDepartment: 'Планируете открытие нового отделения или обновление оборудования?',
    talkToOurTeam: 'Связаться с нашей командой',
    mediaEyebrow: 'Медиа-центр',
    mediaTitle: 'Подробный обзор нашего оборудования и работы.',
    mediaSubtitle: 'Фоторепортажи, демонстрации оборудования и новости компании.',
    reviewsEyebrow: 'Отзывы',
    reviewsTitle: 'Доверие специалистов.',
    reviewsSubtitle: 'Главная оценка нашей работы — отзывы клинических специалистов.',
    catalogueEyebrow: 'Каталог оборудования',
    catalogueTitle: 'Оборудование для реальной клинической практики.',
    catalogueSubtitle: 'Изучите категории оборудования Raamed и найдите подходящее решение.',
    allEquipment: 'Всё оборудование',
    discussThisRange: 'Обсудить эту линейку',
  },
  ja: {
    products: '製品ラインナップ',
    viewAllEquipment: '全機器を見る',
    aboutUs: '会社概要',
    branchNetwork: '拠点ネットワーク',
    customers: '導入実績',
    requestQuote: '見積もりを依頼',
    callUs: 'お電話でのお問い合わせ',
    talkToSpecialist: '専門家に相談',
    exploreEquipment: '医療機器を探す',
    trustedPartners: '信頼される医療パートナー',
    heroTitle: '医療ケアの信頼できる標準。',
    heroSubtitle: '病院やクリニックが最適な医療機器を選択できるよう専門知識と迅速なサポートで支援します。',
    qualityChecked: ' quality Checked 厳格な品質管理',
    regionalSupport: '地域サポート体制',
    equipmentDesk: '機器デスク',
    builtAroundCare: '臨床現場のニーズに合わせて設計。',
    seeFullCatalogue: '全カタログを見る',
    enquireAboutThis: 'この製品について問い合わせる',
    noEquipmentFound: '現在掲載中の機器はありません。',
    betterHandover: '充実した引渡しとサポート',
    equipmentBeginning: '機器の導入は始まりに過ぎません。',
    handoverSubtitle: '選定から設置・アフター h サービスまで、当社のチームが現場に寄り添います。',
    insideClinicalSupport: '臨床サポート体制',
    raamedInField: '現場でのRaamed',
    exploreRaamed: 'Raamedについて知る',
    mediaCentre: 'メディアセンター',
    talkToTeam: 'チームに相談する',
    delhiHq: 'デリー本社',
    monSatHours: '月〜土、9:00〜18:00 IST',
    copyright: '© 2026 Raamed. All rights reserved.',
    patientMonitoring: '生体情報モニタリング',
    surgicalSystems: '手術用システム',
    endoscopySystems: '内視鏡システム',
    respiratoryCare: '呼吸器ケア',
    sterilizationReprocessing: '滅菌・再処理',
    selectLanguage: '言語を選択',
    translateWithGoogle: 'ページ自動翻訳',
    clinicalTechTag: '臨床テクノロジー / 2026',
    precisionCare: '医療現場における高精度。',
    exploreClearerStandard: '現代の臨床環境に適した最新標準。',
    thrMonitor: 'モニター / THR',
    liveReadyInterface: 'リアルタイムUI',
    yearsExpText: '年の臨床経験',
    keyBranchesText: 'インド全域の主要拠点（デリー本社）',
    responseWindowText: '標準レスポンス時間',
    checkBackLater: '後ほど確認いただくか直接お問い合わせください。',
    raamedDescription: 'Raamed – インド全域の医療機関向け信頼できる医療機器。',
    previewComingSoon: 'プレビュー準備中',
    mediaDescription: '臨床ストーリーやチーム情報を発信する専用スペース。',
    branchNetworkEyebrow: '拠点ネットワーク＆オフィス',
    branchNetworkTitle: 'デリー本社からインド全土の医療チームをサポート。',
    branchNetworkSubtitle: 'デリー本社およびパトナ、ラックナウの支社が迅速な配送とサポートを提供します。',
    mainBranchHq: '本社（デリー）',
    patnaBranch: 'パトナ支社',
    lucknowBranch: 'ラックナウ支社',
    landlineHq: '（固定電話 HQ）',
    mobileWhatsapp: '（携帯 / WhatsApp）',
    openInGoogleMaps: 'Googleマップで開く',
    needDirectAssistance: '直接のご相談が必要ですか？',
    connectDirectly: '本社または各地域の担当者に直接お問い合わせください。',
    quickTurnaroundText: '機器の問い合わせやメンテナンスに迅速に対応いたします。',
    callDelhiHqBtn: 'デリー本社に電話: 011-36650267',
    emailBtn: 'メール: Business@raamed.online',
    aboutEyebrow: 'Raamedについて',
    aboutTitle: '明確さと信頼に基づく医療機器パートナー。',
    aboutSubtitle: '医療現場に必要なのは、現場にフィットする機器と継続的なサポートです。',
    practicalExpertise: '実践的な専門知識',
    practicalExpertiseText: '技術的な詳細を分かりやすく説明し確実な臨床選択を支援します。',
    humanSupport: '人による手厚いサポート',
    humanSupportText: 'お問い合わせからアフターサービスまで迅速に対応。',
    longTermThinking: '長期的な視点',
    longTermThinkingText: '機器の信頼性と稼働率を重視したパートナーシップ。',
    peopleBehindTitle: 'パートナーシップを支えるチーム',
    prepareDeliveryTitle: '確実な納品プロセス',
    customersEyebrow: '導入実績',
    customersTitle: '医療現場を支えるチームからの信頼。',
    customersSubtitle: '医師や病院が頼れるパートナーとしてRaamedを選んでいます。',
    workWithRaamed: 'Raamedとの連携',
    planningNewDepartment: '新部門の設立や機器の更新をお考えですか？',
    talkToOurTeam: 'チームに相談する',
    mediaEyebrow: 'メディアセンター',
    mediaTitle: '医療ケアの現場を詳しくご紹介。',
    mediaSubtitle: '写真ストーリーや製品デモをご覧ください。',
    reviewsEyebrow: 'お客様の声',
    reviewsTitle: '医療従事者からの高い評価。',
    reviewsSubtitle: '導入いただいたお客様からの満足度が私たちの実績です。',
    catalogueEyebrow: '機器カタログ',
    catalogueTitle: '臨床現場で活躍する厳選された医療機器。',
    catalogueSubtitle: 'カテゴリーから最適な機器をお選びください。',
    allEquipment: 'すべての機器',
    discussThisRange: 'このシリーズについて相談する',
  },
  pt: {
    products: 'Produtos',
    viewAllEquipment: 'Ver todos os equipamentos',
    aboutUs: 'Sobre nós',
    branchNetwork: 'Rede de filiais',
    customers: 'Clientes',
    requestQuote: 'Solicitar orçamento',
    callUs: 'Ligue para nós',
    talkToSpecialist: 'Falar com um especialista',
    exploreEquipment: 'Explorar equipamentos',
    trustedPartners: 'Parceiros clínicos de confiança',
    heroTitle: 'O padrão confiável para cuidados médicos.',
    heroSubtitle: 'Ajudamos hospitais e clínicas a tomar decisões confiáveis de equipamentos com suporte prático.',
    qualityChecked: 'Qualidade verificada',
    regionalSupport: 'Suporte regional',
    equipmentDesk: 'Central de equipamentos',
    builtAroundCare: 'Construído em torno da rotina clínica.',
    seeFullCatalogue: 'Ver catálogo completo',
    enquireAboutThis: 'Consultar sobre este item',
    noEquipmentFound: 'Nenhum equipamento listado no momento.',
    betterHandover: 'Uma melhor entrega e suporte',
    equipmentBeginning: 'O equipamento é apenas o começo.',
    handoverSubtitle: 'Da seleção ao suporte técnico e instalação, nossa equipe acompanha seu fluxo de trabalho.',
    insideClinicalSupport: 'Suporte clínico',
    raamedInField: 'Raamed em campo',
    exploreRaamed: 'Explorar Raamed',
    mediaCentre: 'Central de mídia',
    talkToTeam: 'Falar com nossa equipe',
    delhiHq: 'Sede em Delhi',
    monSatHours: 'Seg–Sáb, 9:00–18:00 IST',
    copyright: '© 2026 Raamed. Todos os direitos reservados.',
    patientMonitoring: 'Monitoramento de pacientes',
    surgicalSystems: 'Sistemas cirúrgicos',
    endoscopySystems: 'Sistemas de endoscopia',
    respiratoryCare: 'Cuidados respiratórios',
    sterilizationReprocessing: 'Esterilização e reprocessamento',
    selectLanguage: 'Selecionar idioma',
    translateWithGoogle: 'Tradução automática',
    clinicalTechTag: 'Tecnologia Clínica / 2026',
    precisionCare: 'Precisão no ponto de atendimento.',
    exploreClearerStandard: 'Explore um padrão mais claro para ambientes clínicos.',
    thrMonitor: 'MONITOR / THR',
    liveReadyInterface: 'Interface pronta ao vivo',
    yearsExpText: 'Anos de experiência clínica',
    keyBranchesText: 'Principais filiais na Índia (Sede em Delhi)',
    responseWindowText: 'Tempo médio de resposta',
    checkBackLater: 'Verifique mais tarde ou entre em contato diretamente.',
    raamedDescription: 'Raamed – Equipamentos médicos confiáveis na Índia.',
    previewComingSoon: 'Em breve',
    mediaDescription: 'Um espaço dedicado a histórias clínicas e novidades.',
    branchNetworkEyebrow: 'Rede de Filiais e Escritórios',
    branchNetworkTitle: 'Com sede em Delhi, atendendo equipes médicas em toda a Índia.',
    branchNetworkSubtitle: 'Nossa sede principal em Delhi e filiais regionais conectam clínicas a entregas rápidas.',
    mainBranchHq: 'Filial Principal (Sede)',
    patnaBranch: 'Filial Patna',
    lucknowBranch: 'Filial Lucknow',
    landlineHq: '(Fixo Sede)',
    mobileWhatsapp: '(Móvel / WhatsApp)',
    openInGoogleMaps: 'Abrir no Google Maps',
    needDirectAssistance: 'Precisa de assistência direta?',
    connectDirectly: 'Entre em contato diretamente com nossa sede ou representantes.',
    quickTurnaroundText: 'Oferecemos resposta rápida para consultas técnicas e manutenção.',
    callDelhiHqBtn: 'Ligar para Sede Delhi: 011-36650267',
    emailBtn: 'E-mail: Business@raamed.online',
    aboutEyebrow: 'Sobre a Raamed',
    aboutTitle: 'Parceira em equipamentos médicos focada na clareza.',
    aboutSubtitle: 'Equipes médicas precisam de equipamentos adequados e suporte de longo prazo.',
    practicalExpertise: 'Expertise prática',
    practicalExpertiseText: 'Detalhes técnicos traduzidos em decisões clínicas seguras.',
    humanSupport: 'Suporte humano',
    humanSupportText: 'Uma equipe dedicada desde a primeira consulta até o pós-venda.',
    longTermThinking: 'Visão de longo prazo',
    longTermThinkingText: 'Parcerias focadas em confiabilidade e alta disponibilidade.',
    peopleBehindTitle: 'Nossa equipe por trás da parceria',
    prepareDeliveryTitle: 'Como preparamos cada entrega',
    customersEyebrow: 'Clientes',
    customersTitle: 'A confiança de quem cuida da saúde.',
    customersSubtitle: 'Médicos e hospitais escolhem a Raamed por seus equipamentos confiáveis.',
    workWithRaamed: 'Trabalhe com a Raamed',
    planningNewDepartment: 'Planejando um novo departamento ou renovação de equipamentos?',
    talkToOurTeam: 'Falar com nossa equipe',
    mediaEyebrow: 'Central de Mídia',
    mediaTitle: 'Uma visão de perto do nosso trabalho.',
    mediaSubtitle: 'Explore histórias fotográficas, demonstrações e atualizações.',
    reviewsEyebrow: 'Avaliações',
    reviewsTitle: 'Recomendada por profissionais de saúde.',
    reviewsSubtitle: 'A melhor medida do nosso trabalho é o depoimento dos nossos clientes.',
    catalogueEyebrow: 'Catálogo de Equipamentos',
    catalogueTitle: 'Equipamentos selecionados para o trabalho clínico real.',
    catalogueSubtitle: 'Explore as categorias de equipamentos e encontre a solução ideal.',
    allEquipment: 'Todos os equipamentos',
    discussThisRange: 'Consultar esta linha',
  },
  hi: {
    products: 'उत्पाद (Products)',
    viewAllEquipment: 'सभी उपकरण देखें',
    aboutUs: 'हमारे बारे में (About us)',
    branchNetwork: 'शाखा नेटवर्क (Branches)',
    customers: 'हमारे ग्राहक (Customers)',
    requestQuote: 'कोटेशन का अनुरोध करें',
    callUs: 'कॉल करें',
    talkToSpecialist: 'विशेषज्ञ से बात करें',
    exploreEquipment: 'उपकरण देखें',
    trustedPartners: 'विश्वसनीय चिकित्सा भागीदार',
    heroTitle: 'चिकित्सा देखभाल के लिए भरोसेमंद मानक।',
    heroSubtitle: 'हम अस्पतालों, क्लीनिकों और स्वास्थ्य टीमों को आत्मविश्वास से उपकरण निर्णय लेने में मदद करते हैं—व्यावहारिक विशेषज्ञता और प्रतिक्रियाशील सहायता के साथ।',
    qualityChecked: 'गुणवत्ता जाँची गई',
    regionalSupport: 'क्षेत्रीय सहायता',
    equipmentDesk: 'उपकरण डेस्क',
    builtAroundCare: 'आपकी देखभाल के तरीके के अनुसार निर्मित।',
    seeFullCatalogue: 'पूरा कैटलॉग देखें',
    enquireAboutThis: 'इसके बारे में पूछताछ करें',
    noEquipmentFound: 'वर्तमान में कैटलॉग में कोई उपकरण सूचीबद्ध नहीं है।',
    betterHandover: 'बेहतर सेवा और डिलीवरी',
    equipmentBeginning: 'उपकरण तो सिर्फ एक शुरुआत है।',
    handoverSubtitle: 'उत्पाद चयन से लेकर स्थापना और सेवा तक, हमारी टीम आपकी कार्यप्रणाली के करीब रहती है। स्पष्ट सिफारिशें और पारदर्शी सहायता प्राप्त करें।',
    insideClinicalSupport: 'हमारी नैदानिक सहायता',
    raamedInField: 'क्षेत्र में रामेड (Raamed)',
    exploreRaamed: 'रामेड खोजें',
    mediaCentre: 'मीडिया केंद्र',
    talkToTeam: 'हमारी टीम से बात करें',
    delhiHq: 'दिल्ली मुख्यालय',
    monSatHours: 'सोम-शनि, 9:00-18:00 IST',
    copyright: '© 2026 रामेड (RAAMED / RAMMED)। विश्वसनीय चिकित्सा देखभाल के लिए निर्मित। सर्वाधिकार सुरक्षित।',
    patientMonitoring: 'रोगी निगरानी (Patient monitoring)',
    surgicalSystems: 'सर्जिकल उपकरण (Surgical systems)',
    endoscopySystems: 'एंडोस्कोपी प्रणाली (Endoscopy systems)',
    respiratoryCare: 'श्वसन देखभाल (Respiratory care)',
    sterilizationReprocessing: 'नसबंदी एवं पुनर्संस्करण',
    selectLanguage: 'भाषा चुनें',
    translateWithGoogle: 'पेज का स्वतः अनुवाद करें',
    clinicalTechTag: 'नैदानिक तकनीक / 2026',
    precisionCare: 'देखभाल के बिंदु पर सटीकता।',
    exploreClearerStandard: 'आधुनिक नैदानिक वातावरण के लिए एक स्पष्ट मानक देखें।',
    thrMonitor: 'मॉनिटर / THR',
    liveReadyInterface: 'लाइव-रेडी इंटरफ़ेस',
    yearsExpText: 'वर्षों का नैदानिक अनुभव',
    keyBranchesText: 'भारत भर में 3 मुख्य शाखाएं (दिल्ली मुख्यालय)',
    responseWindowText: 'सामान्य प्रतिक्रिया समय (24 घंटे)',
    checkBackLater: 'बाद में पुनः देखें या विशिष्ट उपकरणों की पूछताछ के लिए सीधे हमसे संपर्क करें।',
    raamedDescription: 'रामेड (RAAMED / RAMMED) – भारत भर के अस्पतालों और क्लीनिकों के लिए विश्वसनीय चिकित्सा उपकरण और सहायता।',
    previewComingSoon: 'पूर्वावलोकन जल्द आ रहा है',
    mediaDescription: 'हमारी नैदानिक कहानियों, उपकरण प्रदर्शनों और टीम अपडेट के लिए एक समर्पित स्थान।',
    branchNetworkEyebrow: 'शाखा नेटवर्क और कार्यालय',
    branchNetworkTitle: 'दिल्ली में मुख्यालय, पूरे भारत में सेवाएं।',
    branchNetworkSubtitle: 'दिल्ली में हमारी मुख्य शाखा और पटना और लखनऊ में समर्पित क्षेत्रीय शाखाएँ अस्पतालों को त्वरित उपकरण वितरण से जोड़ती हैं।',
    mainBranchHq: 'मुख्य शाखा (मुख्यालय)',
    patnaBranch: 'पटना शाखा',
    lucknowBranch: 'लखनऊ शाखा',
    landlineHq: '(लैंडलाइन मुख्यालय)',
    mobileWhatsapp: '(मोबाइल / व्हाट्सएप)',
    openInGoogleMaps: 'गूगल मैप्स में खोलें',
    needDirectAssistance: 'प्रत्यक्ष सहायता की आवश्यकता है?',
    connectDirectly: 'हमारे मुख्य कार्यालय या क्षेत्रीय प्रतिनिधियों से सीधे संपर्क करें।',
    quickTurnaroundText: 'हम नैदानिक पूछताछ, उत्पाद प्रदर्शन और तकनीकी रखरखाव के लिए त्वरित प्रतिक्रिया प्रदान करते हैं।',
    callDelhiHqBtn: 'दिल्ली मुख्यालय को कॉल करें: 011-36650267',
    emailBtn: 'ईमेल: Business@raamed.online',
    aboutEyebrow: 'रामेड के बारे में',
    aboutTitle: 'स्पष्टता और विश्वास पर आधारित चिकित्सा उपकरण भागीदार।',
    aboutSubtitle: 'स्वास्थ्य सेवा टीमों को विश्वसनीय उपकरण और निरंतर समर्थन की आवश्यकता होती है।',
    practicalExpertise: 'व्यावहारिक विशेषज्ञता',
    practicalExpertiseText: 'तकनीकी विवरण जिन्हें नैदानिक निर्णयों में आसानी से समझा जा सके।',
    humanSupport: 'व्यक्तिगत सहायता',
    humanSupportText: 'प्रथम पूछताछ से लेकर बिक्री के बाद तक एक जिम्मेदार टीम।',
    longTermThinking: 'दीर्घकालिक सोच',
    longTermThinkingText: 'विश्वसनीयता और निरंतर सेवा पर आधारित साझेदारी।',
    peopleBehindTitle: 'साझेदारी के पीछे हमारी टीम',
    prepareDeliveryTitle: 'हम प्रत्येक डिलीवरी कैसे तैयार करते हैं',
    customersEyebrow: 'हमारे ग्राहक',
    customersTitle: 'चिकित्सा टीमों द्वारा विश्वसनीय।',
    customersSubtitle: 'डॉक्टर, अस्पताल और क्लीनिक रामेड का चयन करते हैं।',
    workWithRaamed: 'रामेड के साथ काम करें',
    planningNewDepartment: 'क्या आप एक नए विभाग या उपकरणों के नवीनीकरण की योजना बना रहे हैं?',
    talkToOurTeam: 'हमारी टीम से बात करें',
    mediaEyebrow: 'मीडिया केंद्र',
    mediaTitle: 'हमारी कार्यप्रणाली पर एक नज़र।',
    mediaSubtitle: 'फोटो कहानियां, उत्पाद प्रदर्शन और टीम अपडेट देखें।',
    reviewsEyebrow: 'समीक्षाएं',
    reviewsTitle: 'चिकित्सा पेशेवरों का विश्वास।',
    reviewsSubtitle: 'हमारे काम का सबसे बड़ा प्रमाण हमारे ग्राहकों की संतुष्टि है।',
    catalogueEyebrow: 'उपकरण कैटलॉग',
    catalogueTitle: 'वास्तविक नैदानिक कार्य के लिए चयनित उपकरण।',
    catalogueSubtitle: 'रामेड की उपकरण श्रेणियों का अन्वेषण करें और सही विकल्प खोजें।',
    allEquipment: 'सभी उपकरण',
    discussThisRange: 'इस श्रेणी पर चर्चा करें',
  },
  bn: {
    products: 'পণ্যসমূহ (Products)',
    viewAllEquipment: 'সমস্ত সরঞ্জাম দেখুন',
    aboutUs: 'আমাদের সম্পর্কে',
    branchNetwork: 'শাখা নেটওয়ার্ক',
    customers: 'গ্রাহকগণ',
    requestQuote: 'কোটেশন অনুরোধ করুন',
    callUs: 'কল করুন',
    talkToSpecialist: 'বিশেষজ্ঞের সাথে কথা বলুন',
    exploreEquipment: 'সরঞ্জাম দেখুন',
    trustedPartners: 'বিশ্বস্ত চিকিৎসা অংশীদার',
    heroTitle: 'চিকিৎসা সেবায় নির্ভরযোগ্য মানদণ্ড।',
    heroSubtitle: 'আমরা হাসপাতাল, ক্লিনিক এবং স্বাস্থ্যসেবা দলগুলিকে নির্ভরযোগ্য সরঞ্জাম নির্বাচনে সহায়তা করি।',
    qualityChecked: 'গুণমান পরীক্ষা করা হয়েছে',
    regionalSupport: 'আঞ্চলিক সহায়তা',
    equipmentDesk: 'সরঞ্জাম ডেস্ক',
    builtAroundCare: 'আপনার সেবার জন্য নির্মিত।',
    seeFullCatalogue: 'সম্পূর্ণ ক্যাটালগ দেখুন',
    enquireAboutThis: 'অনুসন্ধান করুন',
    noEquipmentFound: 'বর্তমানে ক্যাটালগে কোনো সরঞ্জাম তালিকাভুক্ত নেই।',
    betterHandover: 'উন্নত পরিষেবা',
    equipmentBeginning: 'সরঞ্জাম কেবল শুরু মাত্র।',
    handoverSubtitle: 'পণ্য নির্বাচন থেকে ইনস্টলেশন এবং পরিষেবা পর্যন্ত আমাদের দল আপনার সাথেই থাকবে।',
    insideClinicalSupport: 'আমাদের সহায়তা',
    raamedInField: 'মাঠে রামেদ',
    exploreRaamed: 'রামেদ অন্বেষণ করুন',
    mediaCentre: 'মিডিয়া সেন্টার',
    talkToTeam: 'আমাদের দলের সাথে কথা বলুন',
    delhiHq: 'দিল্লি সদর দফতর',
    monSatHours: 'সোম-শনি, ৯:০০-১৮:০০ IST',
    copyright: '© 2026 রামেদ (RAAMED / RAMMED)। সর্বস্বত্ব সংরক্ষিত।',
    patientMonitoring: 'রোগী পর্যবেক্ষণ',
    surgicalSystems: 'সার্জিক্যাল সিস্টেম',
    endoscopySystems: 'এন্ডোস্কোপি সিস্টেম',
    respiratoryCare: 'শ্বাসপ্রশ্বাসের যত্ন',
    sterilizationReprocessing: 'স্টেরিলাইজেশন',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    translateWithGoogle: 'পৃষ্ঠা স্বয়ংক্রিয় অনুবাদ করুন',
    clinicalTechTag: 'চিকিৎসা প্রযুক্তি / 2026',
    precisionCare: 'সেবা কেন্দ্রে নিখুঁত চিকিৎসা মান।',
    exploreClearerStandard: 'আধুনিক চিকিৎসার জন্য একটি স্পষ্ট মানদণ্ড অন্বেষণ করুন।',
    thrMonitor: 'মনিটর / THR',
    liveReadyInterface: 'লাইভ-রেডি ইন্টারফেস',
    yearsExpText: 'বছরের চিকিৎসা অভিজ্ঞতা',
    keyBranchesText: 'ভারত জুড়ে ৩টি প্রধান শাখা (দিল্লি সদর দফতর)',
    responseWindowText: 'সাধারণ প্রতিক্রিয়া সময় (২৪ ঘণ্টা)',
    checkBackLater: 'পরে আবার পরীক্ষা করুন বা সরাসরি আমাদের সাথে যোগাযোগ করুন।',
    raamedDescription: 'রামেদ (RAAMED / RAMMED) – হাসপাতাল ও ক্লিনিকের জন্য নির্ভরযোগ্য চিকিৎসা সরঞ্জাম।',
    previewComingSoon: 'পূর্বরূপ শীঘ্রই আসছে',
    mediaDescription: 'আমাদের গল্প ও আপডেটগুলির জন্য একটি স্থান।',
    branchNetworkEyebrow: 'শাখা নেটওয়ার্ক ও কার্যালয়',
    branchNetworkTitle: 'দিল্লিতে সদর দফতর, সমগ্র ভারতে পরিষেবা।',
    branchNetworkSubtitle: 'দিল্লিতে আমাদের মূল শাখা এবং পাটনা ও লখনউতে আঞ্চলিক শাখাগুলি দ্রুত সরঞ্জাম সরবরাহ করে।',
    mainBranchHq: 'প্রধান শাখা (সদর দফতর)',
    patnaBranch: 'পাটনা শাখা',
    lucknowBranch: 'লখনউ শাখা',
    landlineHq: '(ল্যান্ডলাইন সদর দফতর)',
    mobileWhatsapp: '(মোবাইল / হোয়াটসঅ্যাপ)',
    openInGoogleMaps: 'গুগল ম্যাপে খুলুন',
    needDirectAssistance: 'সরাসরি সহায়তার প্রয়োজন?',
    connectDirectly: 'আমাদের প্রধান কার্যালয় বা আঞ্চলিক প্রতিনিধিদের সাথে সরাসরি যোগাযোগ করুন।',
    quickTurnaroundText: 'আমরা চিকিৎসাসংক্রান্ত অনুসন্ধান এবং রক্ষণাবেক্ষণের জন্য দ্রুত সহায়তা প্রদান করি।',
    callDelhiHqBtn: 'দিল্লি সদর দফতরে কল করুন: 011-36650267',
    emailBtn: 'ইমেল: Business@raamed.online',
    aboutEyebrow: 'রামেদ সম্পর্কে',
    aboutTitle: 'স্পষ্টতার উপর ভিত্তি করে একটি চিকিৎসা সরঞ্জাম অংশীদার।',
    aboutSubtitle: 'স্বাস্থ্যসেবা দলগুলির কাজের উপযোগী সরঞ্জাম এবং নির্ভরযোগ্য সহায়তা প্রয়োজন।',
    practicalExpertise: 'ব্যবহারিক দক্ষতা',
    practicalExpertiseText: 'কারিগরি বিশদ যা আত্মবিশ্বাসী চিকিৎসাসংক্রান্ত সিদ্ধান্তে অনুবাদিত।',
    humanSupport: 'ব্যক্তিগত সহায়তা',
    humanSupportText: 'প্রথম অনুসন্ধান থেকে বিক্রয়োত্তর সেবা পর্যন্ত একটি দায়িত্বশীল দল।',
    longTermThinking: 'দীর্ঘমেয়াদী চিন্তা',
    longTermThinkingText: 'নির্ভরযোগ্যতা এবং কার্যকারিতার উপর ভিত্তি করে অংশীদারিত্ব।',
    peopleBehindTitle: 'অংশীদারিত্বের পেছনে আমাদের দল',
    prepareDeliveryTitle: 'আমরা কীভাবে প্রতিটি ডেলিভারি প্রস্তুত করি',
    customersEyebrow: 'আমাদের গ্রাহকগণ',
    customersTitle: 'স্বাস্থ্যসেবা দলগুলির দ্বারা বিশ্বস্ত।',
    customersSubtitle: 'ডাক্তার, হাসপাতাল এবং ক্লিনিকগুলি নির্ভরযোগ্য সরঞ্জামের জন্য রামেদ বেছে নেয়।',
    workWithRaamed: 'রামেদের সাথে কাজ করুন',
    planningNewDepartment: 'একটি নতুন বিভাগ বা সরঞ্জাম নবায়নের পরিকল্পনা করছেন?',
    talkToOurTeam: 'আমাদের দলের সাথে কথা বলুন',
    mediaEyebrow: 'মিডিয়া সেন্টার',
    mediaTitle: 'আমাদের কাজের একটি বিশদ বিবরণ।',
    mediaSubtitle: 'ফটোগ্রাফি গল্প, পণ্য প্রদর্শন এবং দলের আপডেট অন্বেষণ করুন।',
    reviewsEyebrow: 'পর্যালোচনা',
    reviewsTitle: 'চিকিৎসা পেশাদারদের বিশ্বাস।',
    reviewsSubtitle: 'আমাদের কাজের সেরা পরিমাপ হল গ্রাহকদের মতামত।',
    catalogueEyebrow: 'সরঞ্জাম ক্যাটালগ',
    catalogueTitle: 'প্রকৃত চিকিৎসা কাজের জন্য নির্বাচিত সরঞ্জাম।',
    catalogueSubtitle: 'রামেদের সরঞ্জাম বিভাগ অন্বেষণ করুন এবং সঠিক সরঞ্জাম নির্বাচন করুন।',
    allEquipment: 'সমস্ত সরঞ্জাম',
    discussThisRange: 'এই সরঞ্জাম নিয়ে আলোচনা করুন',
  },
  ta: {
    qualityChecked: 'गुणवत्ता जाँची गई',
    regionalSupport: 'क्षेत्रीय सहायता',
    equipmentDesk: 'उपकरण डेस्क',
    builtAroundCare: 'आपकी देखभाल के तरीके के अनुसार निर्मित।',
    seeFullCatalogue: 'पूरा कैटलॉग देखें',
    enquireAboutThis: 'इसके बारे में पूछताछ करें',
    noEquipmentFound: 'वर्तमान में कैटलॉग में कोई उपकरण सूचीबद्ध नहीं है।',
    betterHandover: 'बेहतर सेवा और डिलीवरी',
    equipmentBeginning: 'उपकरण तो सिर्फ एक शुरुआत है।',
    handoverSubtitle: 'उत्पाद चयन से लेकर स्थापना और सेवा तक, हमारी टीम आपकी कार्यप्रणाली के करीब रहती है। स्पष्ट सिफारिशें और पारदर्शी सहायता प्राप्त करें।',
    insideClinicalSupport: 'हमारी नैदानिक सहायता',
    raamedInField: 'क्षेत्र में रामेड (Raamed)',
    exploreRaamed: 'रामेड खोजें',
    mediaCentre: 'मीडिया केंद्र',
    talkToTeam: 'हमारी टीम से बात करें',
    delhiHq: 'दिल्ली मुख्यालय',
    monSatHours: 'सोम-शनि, 9:00-18:00 IST',
    copyright: '© 2026 रामेड (RAAMED / RAMMED)। विश्वसनीय चिकित्सा देखभाल के लिए निर्मित। सर्वाधिकार सुरक्षित।',
    patientMonitoring: 'रोगी निगरानी (Patient monitoring)',
    surgicalSystems: 'सर्जिकल उपकरण (Surgical systems)',
    endoscopySystems: 'एंडोस्कोपी प्रणाली (Endoscopy systems)',
    respiratoryCare: 'श्वसन देखभाल (Respiratory care)',
    sterilizationReprocessing: 'नसबंदी एवं पुनर्संस्करण',
    selectLanguage: 'भाषा चुनें',
    translateWithGoogle: 'पेज का स्वतः अनुवाद करें',
    clinicalTechTag: 'नैदानिक तकनीक / 2026',
    precisionCare: 'देखभाल के बिंदु पर सटीकता।',
    exploreClearerStandard: 'आधुनिक नैदानिक वातावरण के लिए एक स्पष्ट मानक देखें।',
    thrMonitor: 'मॉनिटर / THR',
    liveReadyInterface: 'लाइव-रेडी इंटरफ़ेस',
    yearsExpText: 'वर्षों का नैदानिक अनुभव',
    keyBranchesText: 'भारत भर में 3 मुख्य शाखाएं (दिल्ली मुख्यालय)',
    responseWindowText: 'सामान्य प्रतिक्रिया समय (24 घंटे)',
    checkBackLater: 'बाद में पुनः देखें या विशिष्ट उपकरणों की पूछताछ के लिए सीधे हमसे संपर्क करें।',
    raamedDescription: 'रामेड (RAAMED / RAMMED) – भारत भर के अस्पतालों और क्लीनिकों के लिए विश्वसनीय चिकित्सा उपकरण और सहायता।',
    previewComingSoon: 'पूर्वावलोकन जल्द आ रहा है',
    mediaDescription: 'हमारी नैदानिक कहानियों, उपकरण प्रदर्शनों और टीम अपडेट के लिए एक समर्पित स्थान।',
  },
  bn: {
    products: 'পণ্যসমূহ (Products)',
    viewAllEquipment: 'সমস্ত সরঞ্জাম দেখুন',
    aboutUs: 'আমাদের সম্পর্কে',
    branchNetwork: 'শাখা নেটওয়ার্ক',
    customers: 'গ্রাহকগণ',
    requestQuote: 'কোটেশন অনুরোধ করুন',
    callUs: 'কল করুন',
    talkToSpecialist: 'বিশেষজ্ঞের সাথে কথা বলুন',
    exploreEquipment: 'সরঞ্জাম দেখুন',
    trustedPartners: 'বিশ্বস্ত চিকিৎসা অংশীদার',
    heroTitle: 'চিকিৎসা সেবায় নির্ভরযোগ্য মানদণ্ড।',
    heroSubtitle: 'আমরা হাসপাতাল, ক্লিনিক এবং স্বাস্থ্যসেবা দলগুলিকে নির্ভরযোগ্য সরঞ্জাম নির্বাচনে সহায়তা করি।',
    qualityChecked: 'গুণমান পরীক্ষা করা হয়েছে',
    regionalSupport: 'আঞ্চলিক সহায়তা',
    equipmentDesk: 'সরঞ্জাম ডেস্ক',
    builtAroundCare: 'আপনার সেবার জন্য নির্মিত।',
    seeFullCatalogue: 'সম্পূর্ণ ক্যাটালগ দেখুন',
    enquireAboutThis: 'অনুসন্ধান করুন',
    noEquipmentFound: 'বর্তমানে ক্যাটালগে কোনো সরঞ্জাম তালিকাভুক্ত নেই।',
    betterHandover: 'উন্নত পরিষেবা',
    equipmentBeginning: 'সরঞ্জাম কেবল শুরু মাত্র।',
    handoverSubtitle: 'পণ্য নির্বাচন থেকে ইনস্টলেশন এবং পরিষেবা পর্যন্ত আমাদের দল আপনার সাথেই থাকবে।',
    insideClinicalSupport: 'আমাদের সহায়তা',
    raamedInField: 'মাঠে রামেদ',
    exploreRaamed: 'রামেদ অন্বেষণ করুন',
    mediaCentre: 'মিডিয়া সেন্টার',
    talkToTeam: 'আমাদের দলের সাথে কথা বলুন',
    delhiHq: 'দিল্লি সদর দফতর',
    monSatHours: 'সোম-শনি, ৯:০০-১৮:০০ IST',
    copyright: '© 2026 রামেদ (RAAMED / RAMMED)। সর্বস্বত্ব সংরক্ষিত।',
    patientMonitoring: 'রোগী পর্যবেক্ষণ',
    surgicalSystems: 'সার্জিক্যাল সিস্টেম',
    endoscopySystems: 'এন্ডোস্কোপি সিস্টেম',
    respiratoryCare: 'শ্বাসপ্রশ্বাসের যত্ন',
    sterilizationReprocessing: 'স্টেরিলাইজেশন',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    translateWithGoogle: 'পৃষ্ঠা স্বয়ংক্রিয় অনুবাদ করুন',
    clinicalTechTag: 'চিকিৎসা প্রযুক্তি / 2026',
    precisionCare: 'সেবা কেন্দ্রে নিখুঁত চিকিৎসা মান।',
    exploreClearerStandard: 'আধুনিক চিকিৎসার জন্য একটি স্পষ্ট মানদণ্ড অন্বেষণ করুন।',
    thrMonitor: 'মনিটর / THR',
    liveReadyInterface: 'লাইভ-রেডি ইন্টারফেস',
    yearsExpText: 'বছরের চিকিৎসা অভিজ্ঞতা',
    keyBranchesText: 'ভারত জুড়ে ৩টি প্রধান শাখা (দিল্লি সদর দফতর)',
    responseWindowText: 'সাধারণ প্রতিক্রিয়া সময় (২৪ ঘণ্টা)',
    checkBackLater: 'পরে আবার পরীক্ষা করুন বা সরাসরি আমাদের সাথে যোগাযোগ করুন।',
    raamedDescription: 'রামেদ (RAAMED / RAMMED) – হাসপাতাল ও ক্লিনিকের জন্য নির্ভরযোগ্য চিকিৎসা সরঞ্জাম।',
    previewComingSoon: 'পূর্বরূপ শীঘ্রই আসছে',
    mediaDescription: 'আমাদের গল্প ও আপডেটগুলির জন্য একটি স্থান।',
  },
  ta: {
    products: 'தயாரிப்புகள் (Products)',
    viewAllEquipment: 'அனைத்து உபகரணங்களையும் காண்க',
    aboutUs: 'எங்களைப் பற்றி',
    branchNetwork: 'கிளை நெட்வொர்க்',
    customers: 'வாடிக்கையாளர்கள்',
    requestQuote: 'விலைப்புள்ளி கேட்கவும்',
    callUs: 'அழைக்கவும்',
    talkToSpecialist: 'நிபுணரிடம் பேசுங்கள்',
    exploreEquipment: 'உபகரணங்களை ஆராயுங்கள்',
    trustedPartners: 'நம்பகமான மருத்துவ கூட்டாளர்கள்',
    heroTitle: 'மருத்துவ பராமரிப்பிற்கான நம்பகமான தரநிலை.',
    heroSubtitle: 'மருத்துவமனைகள் மற்றும் கிளினிக்குகளுக்கு சரியான உபகரணங்களை தேர்வு செய்ய நாங்கள் உதவுகிறோம்.',
    qualityChecked: 'தரம் சரிபார்க்கப்பட்டது',
    regionalSupport: 'மண்டல ஆதரவு',
    equipmentDesk: 'உபகரணங்கள் பிரிவு',
    builtAroundCare: 'உங்கள் பராமரிப்பு தேவைகளுக்காக கட்டப்பட்டது.',
    seeFullCatalogue: 'முழு பட்டியலையும் காண்க',
    enquireAboutThis: 'விசாரிக்கவும்',
    noEquipmentFound: 'தற்போது எந்த உபகரணமும் பட்டியலில் இல்லை.',
    betterHandover: 'சிறந்த சேவை',
    equipmentBeginning: 'உபகரணங்கள் என்பது தொடக்கம் மட்டுமே.',
    handoverSubtitle: 'தயாரிப்பு தேர்வு முதல் நிறுவல் மற்றும் சேவை வரை எங்கள் குழு உங்களுடன் இருக்கும்.',
    insideClinicalSupport: 'எங்கள் மருத்துவ ஆதரவு',
    raamedInField: 'களத்தில் ராமேட்',
    exploreRaamed: 'ராமேட்டை ஆராயுங்கள்',
    mediaCentre: 'ஊடக மையம்',
    talkToTeam: 'எங்கள் குழுவிடம் பேசுங்கள்',
    delhiHq: 'டெல்லி தலைமையகம்',
    monSatHours: 'திங்கள்-சனி, 9:00-18:00 IST',
    copyright: '© 2026 ராமேட் (RAAMED / RAMMED). அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    patientMonitoring: 'நோயாளி கண்காணிப்பு',
    surgicalSystems: 'அறுவை சிகிச்சை அமைப்புகள்',
    endoscopySystems: 'எண்டோஸ்கோபி அமைப்புகள்',
    respiratoryCare: 'சுவாச பராமரிப்பு',
    sterilizationReprocessing: 'விருத்தி அற்ற பராமரிப்பு',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    translateWithGoogle: 'பக்கத்தை தானாக மொழிபெயர்க்கவும்',
    clinicalTechTag: 'மருத்துவ தொழில்நுட்பம் / 2026',
    precisionCare: 'பராமரிப்பு புள்ளியில் துல்லியம்.',
    exploreClearerStandard: 'நவீன மருத்துவ சூழலுக்கான தெளிவான தரநிலையை ஆராயுங்கள்.',
    thrMonitor: 'மானிட்டர் / THR',
    liveReadyInterface: 'லைவ் தயார் இடைமுகம்',
    yearsExpText: 'ஆண்டுகள் மருத்துவ அனுபவம்',
    keyBranchesText: 'இந்தியா முழுவதும் 3 முக்கிய கிளைகள் (டெல்லி தலைமையகம்)',
    responseWindowText: 'வழக்கமான பதில் நேரம் (24 மணிநேரம்)',
    checkBackLater: 'பின்னர் மீண்டும் பார்க்கவும் அல்லது நேரடியாக எங்களை தொடர்பு கொள்ளவும்.',
    raamedDescription: 'ராமேட் – மருத்துவமனைகள் மற்றும் கிளினிக்குகளுக்கான நம்பகமான மருத்துவ உபகரணங்கள்.',
    previewComingSoon: 'முன்னோட்டம் விரைவில் வரும்',
    mediaDescription: 'எங்கள் மருத்துவக் கதைகள் மற்றும் அறிவிப்புகளுக்கான இடம்.',
  },
  mr: {
    products: 'उत्पादने (Products)',
    viewAllEquipment: 'सर्व उपकरणे पहा',
    aboutUs: 'आमच्याबद्दल (About us)',
    branchNetwork: 'शाखा नेटवर्क (Branches)',
    customers: 'ग्राहक (Customers)',
    requestQuote: 'कोटेशनची विनंती करा',
    callUs: 'कॉल करा',
    talkToSpecialist: 'तज्ञांशी बोला',
    exploreEquipment: 'उपकरणे पहा',
    trustedPartners: 'विश्वसनीय वैद्यकीय भागीदार',
    heroTitle: 'वैद्यकीय देखभालीसाठी विश्वासार्ह मानक.',
    heroSubtitle: 'आम्ही रुग्णालये आणि क्लिनिकांना योग्य उपकरणांची निवड करण्यास मदत करतो.',
    qualityChecked: 'गुणवत्ता तपासलेली',
    regionalSupport: 'प्रादेशिक मदत',
    equipmentDesk: 'उपकरणे विभाग',
    builtAroundCare: 'तुमच्या सेवेसाठी बनवलेले.',
    seeFullCatalogue: 'पूर्ण कॅटलॉग पहा',
    enquireAboutThis: 'याबद्दल चौकशी करा',
    noEquipmentFound: 'सध्या कॅटलॉगमध्ये कोणतीही उपकरणे सूचीबद्ध नाहीत.',
    betterHandover: 'उत्कृष्ट सेवा',
    equipmentBeginning: 'उपकरणे ही फक्त सुरुवात आहे.',
    handoverSubtitle: 'उत्पादन निवडीपासून ते इन्स्टॉलेशन आणि सेवेपर्यंत आमची टीम तुमच्यासोबत राहते.',
    insideClinicalSupport: 'आमची वैद्यकीय मदत',
    raamedInField: 'क्षेत्रात रामेड',
    exploreRaamed: 'रामेड शोधा',
    mediaCentre: 'मीडिया सेंटर',
    talkToTeam: 'आमच्या टीमशी बोला',
    delhiHq: 'दिल्ली मुख्यालय',
    monSatHours: 'सोम-शनि, 9:00-18:00 IST',
    copyright: '© 2026 रामेड (RAAMED / RAMMED). सर्व हक्क राखीव.',
    patientMonitoring: 'रुग्ण देखरेख',
    surgicalSystems: 'सर्जिकल सिस्टीम',
    endoscopySystems: 'एंडोस्कोपी सिस्टीम',
    respiratoryCare: 'श्वसन काळजी',
    sterilizationReprocessing: 'निर्जंतुकीकरण',
    selectLanguage: 'भाषा निवडा',
    translateWithGoogle: 'पृष्ठाचे आपोआप भाषांतर करा',
    clinicalTechTag: 'वैद्यकीय तंत्रज्ञान / 2026',
    precisionCare: 'देखभालीच्या ठिकाणी अचूकता.',
    exploreClearerStandard: 'आधुनिक वैद्यकीय वातावरणासाठी एक स्पष्ट मानक शोधा.',
    thrMonitor: 'मॉनिटर / THR',
    liveReadyInterface: 'लाइव्ह-रेडी इंटरफेस',
    yearsExpText: 'वर्षांचा वैद्यकीय अनुभव',
    keyBranchesText: 'भारतभरात ३ मुख्य शाखा (दिल्ली मुख्यालय)',
    responseWindowText: 'सर्वसाधारण प्रतिसाद वेळ (२४ तास)',
    checkBackLater: 'नंतर पुन्हा तपासा किंवा थेट आमच्याशी संपर्क साधा.',
    raamedDescription: 'रामेड – रुग्णालये आणि क्लिनिकसाठी विश्वासार्ह वैद्यकीय उपकरणे.',
    previewComingSoon: 'पूर्वावलोकन लवकरच येत आहे',
    mediaDescription: 'आमच्या स्टोरीज आणि टीम अपडेटसाठी एक समर्पित जागा.',
  },
  ta: {
    products: 'தயாரிப்புகள் (Products)',
    viewAllEquipment: 'அனைத்து உபகரணங்களையும் காண்க',
    aboutUs: 'எங்களைப் பற்றி',
    branchNetwork: 'கிளை நெட்வொர்க்',
    customers: 'வாடிக்கையாளர்கள்',
    requestQuote: 'விலைப்புள்ளி கேட்கவும்',
    callUs: 'அழைக்கவும்',
    talkToSpecialist: 'நிபுணரிடம் பேசுங்கள்',
    exploreEquipment: 'உபகரணங்களை ஆராயுங்கள்',
    trustedPartners: 'நம்பகமான மருத்துவ கூட்டாளர்கள்',
    heroTitle: 'மருத்துவ பராமரிப்பிற்கான நம்பகமான தரநிலை.',
    heroSubtitle: 'மருத்துவமனைகள் மற்றும் கிளினிக்குகளுக்கு சரியான உபகரணங்களை தேர்வு செய்ய நாங்கள் உதவுகிறோம்.',
    qualityChecked: 'தரம் சரிபார்க்கப்பட்டது',
    regionalSupport: 'மண்டல ஆதரவு',
    equipmentDesk: 'உபகரணங்கள் பிரிவு',
    builtAroundCare: 'உங்கள் பராமரிப்பு தேவைகளுக்காக கட்டப்பட்டது.',
    seeFullCatalogue: 'முழு பட்டியலையும் காண்க',
    enquireAboutThis: 'விசாரிக்கவும்',
    noEquipmentFound: 'தற்போது எந்த உபகரணமும் பட்டியலில் இல்லை.',
    betterHandover: 'சிறந்த சேவை',
    equipmentBeginning: 'உபகரணங்கள் என்பது தொடக்கம் மட்டுமே.',
    handoverSubtitle: 'தயாரிப்பு தேர்வு முதல் நிறுவல் மற்றும் சேவை வரை எங்கள் குழு உங்களுடன் இருக்கும்.',
    insideClinicalSupport: 'எங்கள் மருத்துவ ஆதரவு',
    raamedInField: 'களத்தில் ராமேட்',
    exploreRaamed: 'ராமேட்டை ஆராயுங்கள்',
    mediaCentre: 'ஊடக மையம்',
    talkToTeam: 'எங்கள் குழுவிடம் பேசுங்கள்',
    delhiHq: 'டெல்லி தலைமையகம்',
    monSatHours: 'திங்கள்-சனி, 9:00-18:00 IST',
    copyright: '© 2026 ராமேட் (RAAMED / RAMMED). அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    patientMonitoring: 'நோயாளி கண்காணிப்பு',
    surgicalSystems: 'அறுவை சிகிச்சை அமைப்புகள்',
    endoscopySystems: 'எண்டோஸ்கோபி அமைப்புகள்',
    respiratoryCare: 'சுவாச பராமரிப்பு',
    sterilizationReprocessing: 'விருத்தி அற்ற பராமரிப்பு',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    translateWithGoogle: 'பக்கத்தை தானாக மொழிபெயர்க்கவும்',
  },
  mr: {
    products: 'उत्पादने (Products)',
    viewAllEquipment: 'सर्व उपकरणे पहा',
    aboutUs: 'आमच्याबद्दल (About us)',
    branchNetwork: 'शाखा नेटवर्क (Branches)',
    customers: 'ग्राहक (Customers)',
    requestQuote: 'कोटेशनची विनंती करा',
    callUs: 'कॉल करा',
    talkToSpecialist: 'तज्ञांशी बोला',
    exploreEquipment: 'उपकरणे पहा',
    trustedPartners: 'विश्वसनीय वैद्यकीय भागीदार',
    heroTitle: 'वैद्यकीय देखभालीसाठी विश्वासार्ह मानक.',
    heroSubtitle: 'आम्ही रुग्णालये आणि क्लिनिकांना योग्य उपकरणांची निवड करण्यास मदत करतो.',
    qualityChecked: 'गुणवत्ता तपासलेली',
    regionalSupport: 'प्रादेशिक मदत',
    equipmentDesk: 'उपकरणे विभाग',
    builtAroundCare: 'तुमच्या सेवेसाठी बनवलेले.',
    seeFullCatalogue: 'पूर्ण कॅटलॉग पहा',
    enquireAboutThis: 'याबद्दल चौकशी करा',
    noEquipmentFound: 'सध्या कॅटलॉगमध्ये कोणतीही उपकरणे सूचीबद्ध नाहीत.',
    betterHandover: 'उत्कृष्ट सेवा',
    equipmentBeginning: 'उपकरणे ही फक्त सुरुवात आहे.',
    handoverSubtitle: 'उत्पादन निवडीपासून ते इन्स्टॉलेशन आणि सेवेपर्यंत आमची टीम तुमच्यासोबत राहते.',
    insideClinicalSupport: 'आमची वैद्यकीय मदत',
    raamedInField: 'क्षेत्रात रामेड',
    exploreRaamed: 'रामेड शोधा',
    mediaCentre: 'मीडिया सेंटर',
    talkToTeam: 'आमच्या टीमशी बोला',
    delhiHq: 'दिल्ली मुख्यालय',
    monSatHours: 'सोम-शनि, 9:00-18:00 IST',
    copyright: '© 2026 रामेड (RAAMED / RAMMED). सर्व हक्क राखीव.',
    patientMonitoring: 'रुग्ण देखरेख',
    surgicalSystems: 'सर्जिकल सिस्टीम',
    endoscopySystems: 'एंडोस्कोपी सिस्टीम',
    respiratoryCare: 'श्वसन काळजी',
    sterilizationReprocessing: 'निर्जंतुकीकरण',
    selectLanguage: 'भाषा निवडा',
    translateWithGoogle: 'पृष्ठाचे आपोआप भाषांतर करा',
  },
}

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => undefined,
  t: (key: string) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    const saved = localStorage.getItem('raamed_language') as Language
    if (saved && translations[saved]) {
      setLanguageState(saved)
      document.documentElement.lang = saved
      document.documentElement.dir = saved === 'ar' ? 'rtl' : 'ltr'
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('raamed_language', lang)
    document.documentElement.lang = lang
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
  }

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}



